In [1]:
import kagglehub
# You may need to re-run this cell after logging in.
kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Kaggle credentials set.
Kaggle credentials successfully validated.

In [2]:
path = kagglehub.competition_download('home-credit-credit-risk-model-stability')

Downloading to /root/.cache/kagglehub/competitions/home-credit-credit-risk-model-stability.archive...

100%|██████████| 3.14G/3.14G [00:24<00:00, 136MB/s]

Extracting files...

In [3]:
!ln -s "$path" /content/home_credit

In [4]:
import os
from google.colab import userdata
github_token = userdata.get('github_token')
dagshub_token = userdata.get('dagshub_token')
os.environ["DAGSHUB_TOKEN"] = userdata.get("dagshub_token")
%cd /content
!git clone https://github.com/Hassan-ElBanna/Loan-Default-Prediction-Risk-Analysis.git
%cd Loan-Default-Prediction-Risk-Analysis
!git remote set-url origin https://Hassan-ElBanna:{github_token}@github.com/Hassan-ElBanna/Loan-Default-Prediction-Risk-Analysis.git
!python /content/Loan-Default-Prediction-Risk-Analysis/Scripts/setup_colab.py

/content
Cloning into 'Loan-Default-Prediction-Risk-Analysis'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 53 (delta 20), reused 26 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (53/53), 70.13 KiB | 1.49 MiB/s, done.
Resolving deltas: 100% (20/20), done.
/content/Loan-Default-Prediction-Risk-Analysis
>>> pip install dvc
Collecting dvc
  Downloading dvc-3.67.1-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from dvc) (26.1.0)
Collecting celery (from dvc)
  Downloading celery-5.6.3-py3-none-any.whl.metadata (23 kB)
Collecting colorama>=0.3.9 (from dvc)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting configobj>=5.0.9 (from dvc)
  Downloading configobj-5.0.9-py2.py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: distro>=1.3 in /usr/local/lib/python3.13/dist-packages (from dvc) (1.9.0)
Collecting dpath<3,>=2.1.0 (from dvc)
  Downloading dpath-2.2.0-py3-none-any.whl.metadata (15 kB)
Collecting dulwich (from dvc)
  Downloading dulwich-1.2.17-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (6.0 kB)
Collecting dvc-data<3.19.0,>=3.18.2 (from dvc)
  Downloading dvc_data-3.18.3-py3-none-any.whl.metadata (4.9 kB)
Collecting dvc-http>=2.29.0 (from dvc)
  Downloading dvc_http-2.32.0-py3-none-any.whl.metadata (1.3 kB)
Collecting dvc-objects (from dvc)
  Downloading dvc_objects-5.2.0-py3-none-any.whl.metadata (3.9 kB)
Collecting dvc-render<2,>=1.0.1 (from dvc)
  Downloading dvc_render-1.0.2-py3-none-any.whl.metadata (5.4 kB)
Collecting dvc-studio-client<1,>=0.21 (from dvc)
  Downloading dvc_studio_client-0.23.0-py3-none-any.whl.metadata (4.4 kB)
Collecting dvc-task<1,>=0.3.0 (from dvc)
  Downloading dvc_task-0.40.2-py3-none-any.whl.metadata (10.0 kB)
Collecting flatten-dict<1,>=0.4.1 (from dvc)
  Downloading flatten_dict-0.5.0-py3-none-any.whl.metadata (8.9 kB)
Collecting flufl.lock<10,>=8.1.0 (from dvc)
  Downloading flufl_lock-9.2.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: fsspec>=2024.2.0 in /usr/local/lib/python3.13/dist-packages (from dvc) (2025.12.0)
Collecting funcy>=1.14 (from dvc)
  Downloading funcy-2.1-py3-none-any.whl.metadata (6.3 kB)
Collecting grandalf<1,>=0.7 (from dvc)
  Downloading grandalf-0.8-py3-none-any.whl.metadata (1.7 kB)
Collecting gto<2,>=1.6.0 (from dvc)
  Downloading gto-1.10.1-py3-none-any.whl.metadata (4.8 kB)
Collecting hydra-core>=1.1 (from dvc)
  Downloading hydra_core-1.3.7-py3-none-any.whl.metadata (5.7 kB)
Collecting iterative-telemetry>=0.0.7 (from dvc)
  Downloading iterative_telemetry-0.0.10-py3-none-any.whl.metadata (4.1 kB)
Collecting kombu (from dvc)
  Downloading kombu-5.6.2-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.13/dist-packages (from dvc) (3.7)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.13/dist-packages (from dvc) (2.3.1)
Requirement already satisfied: packaging>=19 in /usr/local/lib/python3.13/dist-packages (from dvc) (26.3)
Collecting pathspec<2,>=0.10.3 (from dvc)
  Downloading pathspec-1.1.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: platformdirs<5,>=3.1.1 in /usr/local/lib/python3.13/dist-packages (from dvc) (4.12.2)
Requirement already satisfied: psutil>=5.8 in /usr/local/lib/python3.13/dist-packages (from dvc) (5.9.5)
Requirement already satisfied: pydot>=1.2.4 in /usr/local/lib/python3.13/dist-packages (from dvc) (4.0.1)
Collecting pygtrie>=2.3.2 (from dvc)
  Downloading pygtrie-2.6.2-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pyparsing>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from dvc) (3.3.3)
Requirement already satisfied: requests>=2.22 in /usr/local/lib/python3.13/dist-packages (from dvc) (2.32.4)
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.13/dist-packages (from dvc) (13.9.4)
Collecting ruamel.yaml>=0.17.11 (from dvc)
  Downloading ruamel_yaml-0.19.1-py3-none-any.whl.metadata (16 kB)
Collecting scmrepo<4,>=3.5.2 (from dvc)
  Downloading scmrepo-3.6.2-py3-none-any.whl.metadata (4.8 kB)
Collecting shortuuid>=0.5 (from dvc)
  Downloading shortuuid-1.0.13-py3-none-any.whl.metadata (5.8 kB)
Collecting shtab<2,>=1.3.4 (from dvc)
  Downloading shtab-1.12.1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.13/dist-packages (from dvc) (0.9.0)
Requirement already satisfied: tomlkit>=0.11.1 in /usr/local/lib/python3.13/dist-packages (from dvc) (0.14.0)
Requirement already satisfied: tqdm<5,>=4.63.1 in /usr/local/lib/python3.13/dist-packages (from dvc) (4.67.3)
Collecting voluptuous>=0.11.7 (from dvc)
  Downloading voluptuous-0.16.0-py3-none-any.whl.metadata (20 kB)
Collecting zc.lockfile>=1.2.1 (from dvc)
  Downloading zc_lockfile-4.0-py3-none-any.whl.metadata (6.6 kB)
Collecting dictdiffer>=0.8.1 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Downloading dictdiffer-0.10.0-py3-none-any.whl.metadata (2.9 kB)
Collecting diskcache>=5.2.1 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting sqltrie<1,>=0.11.0 (from dvc-data<3.19.0,>=3.18.2->dvc)
  Downloading sqltrie-0.11.3-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: orjson<4,>=3 in /usr/local/lib/python3.13/dist-packages (from dvc-data<3.19.0,>=3.18.2->dvc) (3.12.0)
Collecting aiohttp-retry>=2.5.0 (from dvc-http>=2.29.0->dvc)
  Downloading aiohttp_retry-2.9.1-py3-none-any.whl.metadata (8.8 kB)
Collecting billiard<5.0,>=4.2.1 (from celery->dvc)
  Downloading billiard-4.3.1-py3-none-any.whl.metadata (5.0 kB)
Collecting vine<6.0,>=5.1.0 (from celery->dvc)
  Downloading vine-5.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: click<9.0,>=8.1.2 in /usr/local/lib/python3.13/dist-packages (from celery->dvc) (8.5.0)
Collecting click-didyoumean>=0.3.0 (from celery->dvc)
  Downloading click_didyoumean-0.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting click-repl>=0.2.0 (from celery->dvc)
  Downloading click_repl-0.4.1-py3-none-any.whl.metadata (3.7 kB)
Collecting click-plugins>=1.1.1 (from celery->dvc)
  Downloading click_plugins-1.1.1.2-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from celery->dvc) (2.9.0.post0)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.13/dist-packages (from celery->dvc) (5.4.4)
Requirement already satisfied: atpublic in /usr/local/lib/python3.13/dist-packages (from flufl.lock<10,>=8.1.0->dvc) (5.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.13/dist-packages (from gto<2,>=1.6.0->dvc) (0.4)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.13/dist-packages (from gto<2,>=1.6.0->dvc) (2.13.5)
Collecting pydantic-settings>=2 (from gto<2,>=1.6.0->dvc)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Collecting semver>=2.13.0 (from gto<2,>=1.6.0->dvc)
  Downloading semver-3.1.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.13/dist-packages (from hydra-core>=1.1->dvc) (4.9.3)
Collecting appdirs (from iterative-telemetry>=0.0.7->dvc)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from iterative-telemetry>=0.0.7->dvc) (4.0.7)
Collecting amqp<6.0.0,>=5.1.1 (from kombu->dvc)
  Downloading amqp-5.4.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: tzdata>=2025.2 in /usr/local/lib/python3.13/dist-packages (from kombu->dvc) (2026.4)
Requirement already satisfied: PyYAML>=5.1.0 in /usr/local/lib/python3.13/dist-packages (from omegaconf->dvc) (6.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.22->dvc) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.22->dvc) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.22->dvc) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.22->dvc) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=12->dvc) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=12->dvc) (2.21.0)
Collecting gitpython>3 (from scmrepo<4,>=3.5.2->dvc)
  Downloading gitpython-3.2.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pygit2>=1.14.0 in /usr/local/lib/python3.13/dist-packages (from scmrepo<4,>=3.5.2->dvc) (1.20.1)
Collecting asyncssh<3,>=2.13.1 (from scmrepo<4,>=3.5.2->dvc)
  Downloading asyncssh-2.24.1-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from zc.lockfile>=1.2.1->dvc) (80.10.2)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.13/dist-packages (from aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (3.14.3)
Requirement already satisfied: cryptography>=48.0.1 in /usr/local/lib/python3.13/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (50.0.2)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from asyncssh<3,>=2.13.1->scmrepo<4,>=3.5.2->dvc) (4.16.0)
Requirement already satisfied: prompt_toolkit>=3.0.36 in /usr/local/lib/python3.13/dist-packages (from click-repl>=0.2.0->celery->dvc) (3.0.53)
Collecting gitdb<5,>=4.0.1 (from gitpython>3->scmrepo<4,>=3.5.2->dvc)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=12->dvc) (0.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2->gto<2,>=1.6.0->dvc) (0.4.4)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings>=2->gto<2,>=1.6.0->dvc) (1.2.3)
Requirement already satisfied: cffi>=2.0 in /usr/local/lib/python3.13/dist-packages (from pygit2>=1.14.0->scmrepo<4,>=3.5.2->dvc) (2.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->celery->dvc) (1.17.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->aiohttp-retry>=2.5.0->dvc-http>=2.29.0->dvc) (1.25.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0->pygit2>=1.14.0->scmrepo<4,>=3.5.2->dvc) (3.0)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython>3->scmrepo<4,>=3.5.2->dvc)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: wcwidth>=0.1.4 in /usr/local/lib/python3.13/dist-packages (from prompt_toolkit>=3.0.36->click-repl>=0.2.0->celery->dvc) (0.9.1)
Downloading dvc-3.67.1-py3-none-any.whl (470 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 470.1/470.1 kB 10.6 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading configobj-5.0.9-py2.py3-none-any.whl (35 kB)
Downloading dpath-2.2.0-py3-none-any.whl (17 kB)
Downloading dvc_data-3.18.3-py3-none-any.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 5.5 MB/s eta 0:00:00
Downloading dvc_http-2.32.0-py3-none-any.whl (12 kB)
Downloading dvc_objects-5.2.0-py3-none-any.whl (33 kB)
Downloading dvc_render-1.0.2-py3-none-any.whl (22 kB)
Downloading dvc_studio_client-0.23.0-py3-none-any.whl (16 kB)
Downloading dvc_task-0.40.2-py3-none-any.whl (21 kB)
Downloading celery-5.6.3-py3-none-any.whl (451 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 451.2/451.2 kB 24.8 MB/s eta 0:00:00
Downloading flatten_dict-0.5.0-py3-none-any.whl (9.9 kB)
Downloading flufl_lock-9.2.0-py3-none-any.whl (11 kB)
Downloading funcy-2.1-py3-none-any.whl (29 kB)
Downloading grandalf-0.8-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 2.9 MB/s eta 0:00:00
Downloading gto-1.10.1-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 3.3 MB/s eta 0:00:00
Downloading hydra_core-1.3.7-py3-none-any.whl (168 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.8/168.8 kB 13.2 MB/s eta 0:00:00
Downloading iterative_telemetry-0.0.10-py3-none-any.whl (10 kB)
Downloading kombu-5.6.2-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.2/214.2 kB 16.9 MB/s eta 0:00:00
Downloading vine-5.1.0-py3-none-any.whl (9.6 kB)
Downloading pathspec-1.1.1-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 3.9 MB/s eta 0:00:00
Downloading pygtrie-2.6.2-py3-none-any.whl (33 kB)
Downloading ruamel_yaml-0.19.1-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 5.5 MB/s eta 0:00:00
Downloading scmrepo-3.6.2-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.2/74.2 kB 5.5 MB/s eta 0:00:00
Downloading dulwich-1.2.17-cp313-cp313-manylinux_2_28_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 42.4 MB/s eta 0:00:00
Downloading shortuuid-1.0.13-py3-none-any.whl (10 kB)
Downloading shtab-1.12.1-py3-none-any.whl (22 kB)
Downloading voluptuous-0.16.0-py3-none-any.whl (31 kB)
Downloading zc_lockfile-4.0-py3-none-any.whl (9.1 kB)
Downloading aiohttp_retry-2.9.1-py3-none-any.whl (10.0 kB)
Downloading amqp-5.4.1-py3-none-any.whl (51 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.9/51.9 kB 3.3 MB/s eta 0:00:00
Downloading asyncssh-2.24.1-py3-none-any.whl (382 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 382.5/382.5 kB 22.6 MB/s eta 0:00:00
Downloading billiard-4.3.1-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 6.0 MB/s eta 0:00:00
Downloading click_didyoumean-0.3.1-py3-none-any.whl (3.6 kB)
Downloading click_plugins-1.1.1.2-py2.py3-none-any.whl (11 kB)
Downloading click_repl-0.4.1-py3-none-any.whl (14 kB)
Downloading dictdiffer-0.10.0-py3-none-any.whl (16 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.8 MB/s eta 0:00:00
Downloading gitpython-3.2.0-py3-none-any.whl (228 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.5/228.5 kB 18.1 MB/s eta 0:00:00
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 5.4 MB/s eta 0:00:00
Downloading semver-3.1.0-py3-none-any.whl (18 kB)
Downloading sqltrie-0.11.3-py3-none-any.whl (17 kB)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 3.7 MB/s eta 0:00:00
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Installing collected packages: funcy, appdirs, zc.lockfile, voluptuous, vine, smmap, shtab, shortuuid, semver, ruamel.yaml, pygtrie, pathspec, grandalf, flufl.lock, flatten-dict, dvc-render, dvc-objects, dulwich, dpath, diskcache, dictdiffer, configobj, colorama, click-plugins, click-didyoumean, billiard, sqltrie, iterative-telemetry, hydra-core, gitdb, dvc-studio-client, click-repl, amqp, pydantic-settings, kombu, gitpython, dvc-data, asyncssh, aiohttp-retry, scmrepo, dvc-http, celery, gto, dvc-task, dvc
Successfully installed aiohttp-retry-2.9.1 amqp-5.4.1 appdirs-1.4.4 asyncssh-2.24.1 billiard-4.3.1 celery-5.6.3 click-didyoumean-0.3.1 click-plugins-1.1.1.2 click-repl-0.4.1 colorama-0.4.6 configobj-5.0.9 dictdiffer-0.10.0 diskcache-5.6.3 dpath-2.2.0 dulwich-1.2.17 dvc-3.67.1 dvc-data-3.18.3 dvc-http-2.32.0 dvc-objects-5.2.0 dvc-render-1.0.2 dvc-studio-client-0.23.0 dvc-task-0.40.2 flatten-dict-0.5.0 flufl.lock-9.2.0 funcy-2.1 gitdb-4.0.12 gitpython-3.2.0 grandalf-0.8 gto-1.10.1 hydra-core-1.3.7 iterative-telemetry-0.0.10 kombu-5.6.2 pathspec-1.1.1 pydantic-settings-2.15.0 pygtrie-2.6.2 ruamel.yaml-0.19.1 scmrepo-3.6.2 semver-3.1.0 shortuuid-1.0.13 shtab-1.12.1 smmap-5.0.3 sqltrie-0.11.3 vine-5.1.0 voluptuous-0.16.0 zc.lockfile-4.0
>>> git config --global user.name "Hassan"
>>> git config --global user.email "200016662@must.edu.eg"
>>> dvc remote remove storage || true
>>> dvc remote add -d storage https://dagshub.com/hmelbanna100/Loan_Default_Prediction_Risk_Analysis.dvc
Setting 'storage' as a default remote.
>>> dvc remote modify storage --local auth basic
>>> dvc remote modify storage --local user hmelbanna100
>>> dvc remote modify storage --local password fc475011c0c5d567d49d08dd2da5c32e922214de
>>> dvc pull
Collecting          |1.00 [00:00, 87.2entry/s]
Fetching
!
  0% |          |0/? [00:00<?,    ?files/s]

!
  0% |          |0/? [00:00<?,    ?files/s]
100% 1/1 [00:00<00:00,  1.71files/s{'info': ''}]

Fetching from https:   0% 0/1 [00:00<?, ?file/s]
Fetching from https:   0% 0/1 [00:00<?, ?file/s{'info': ''}]

!

          |0.00 [00:00,        ?B/s]

          |1.34M [00:00,    13.8MB/s]

          |13.3M [00:00,    76.4MB/s]

          |28.1M [00:00,     104MB/s]

          |37.1M [00:00,     100MB/s]

          |44.1M [00:05,    5.31MB/s]


Fetching from https: 100% 1/1 [00:05<00:00,  5.70s/file{'info': ''}]
Fetching
Building workspace index          |1.00 [00:00, 33.9entry/s]
Comparing indexes          |3.00 [00:00,  862entry/s]
Applying changes          |1.00 [00:00,  29.3file/s]
A       data/train.csv
1 file fetched and 1 file added
>>> git pull
Already up to date.
Setup completed successfully.

In [5]:
import polars as pl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

# Train sets

In [6]:
# Train sets

# depth = 0
base_train = pl.read_csv('/content/home_credit/csv_files/train/train_base.csv')
static_1_train = pl.read_csv('/content/home_credit/csv_files/train/train_static_0_0.csv')
static_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_static_0_1.csv')
static_cb_train = pl.read_csv('/content/home_credit/csv_files/train/train_static_cb_0.csv')

In [7]:
# depth = 1
applprev_1_0_train = pl.read_csv('/content/home_credit/csv_files/train/train_applprev_1_0.csv')
applprev_1_1_trian = pl.read_csv('/content/home_credit/csv_files/train/train_applprev_1_1.csv')

other_train = pl.read_csv('/content/home_credit/csv_files/train/train_other_1.csv')

tax_registry_a_train = pl.read_csv('/content/home_credit/csv_files/train/train_tax_registry_a_1.csv')
tax_registry_b_train = pl.read_csv('/content/home_credit/csv_files/train/train_tax_registry_b_1.csv')
tax_registry_c_train = pl.read_csv('/content/home_credit/csv_files/train/train_tax_registry_c_1.csv')

credit_bureau_a_1_0_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_1_0.csv')
credit_bureau_a_1_1_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_1_1.csv')
credit_bureau_a_1_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_1_2.csv')
credit_bureau_a_1_3_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_1_3.csv')
credit_bureau_b_1_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_b_1.csv')

deposit_trian = pl.read_csv('/content/home_credit/csv_files/train/train_deposit_1.csv')

person_1_train = pl.read_csv('/content/home_credit/csv_files/train/train_person_1.csv')

debitcard_trian = pl.read_csv('/content/home_credit/csv_files/train/train_debitcard_1.csv')

In [8]:
# depth = 2
person_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_person_2.csv')

applprev_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_applprev_2.csv')

credit_bureau_a_2_0_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_0.csv')
credit_bureau_a_2_1_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_1.csv')
# credit_bureau_a_2_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_2.csv')
# credit_bureau_a_2_3_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_3.csv')
# credit_bureau_a_2_4_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_4.csv')
# credit_bureau_a_2_5_trian = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_5.csv')
# credit_bureau_a_2_6_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_6.csv')
# credit_bureau_a_2_7_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_7.csv')
# credit_bureau_a_2_8_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_8.csv')
# credit_bureau_a_2_9_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_9.csv')
# credit_bureau_a_2_10_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_10.csv')

credit_bureau_b_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_b_2.csv')

# Test sets

In [9]:
# test sets

# depth = 0
base_test = pl.read_csv('/content/home_credit/csv_files/test/test_base.csv')
static_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_static_0_0.csv')
static_2_test = pl.read_csv('/content/home_credit/csv_files/test/test_static_0_1.csv')
static_cb_test = pl.read_csv('/content/home_credit/csv_files/test/test_static_cb_0.csv')

In [10]:
# depth = 1
applprev_1_0_test = pl.read_csv('/content/home_credit/csv_files/test/test_applprev_1_0.csv')
applprev_1_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_applprev_1_1.csv')

other_test = pl.read_csv('/content/home_credit/csv_files/test/test_other_1.csv')

tax_registry_a_test = pl.read_csv('/content/home_credit/csv_files/test/test_tax_registry_a_1.csv')
tax_registry_b_test = pl.read_csv('/content/home_credit/csv_files/test/test_tax_registry_b_1.csv')
tax_registry_c_test = pl.read_csv('/content/home_credit/csv_files/test/test_tax_registry_c_1.csv')

credit_bureau_a_1_0_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_1_0.csv')
credit_bureau_a_1_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_1_1.csv')
credit_bureau_a_1_2_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_1_2.csv')
credit_bureau_a_1_3_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_1_3.csv')
credit_bureau_b_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_b_1.csv')

deposit_test = pl.read_csv('/content/home_credit/csv_files/test/test_deposit_1.csv')

person_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_person_1.csv')

debitcard_test = pl.read_csv('/content/home_credit/csv_files/test/test_debitcard_1.csv')

In [11]:
# depth = 2
person_2_test = pl.read_csv('/content/home_credit/csv_files/test/test_person_2.csv')

applprev_2_test = pl.read_csv('/content/home_credit/csv_files/test/test_applprev_2.csv')

credit_bureau_a_2_0_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_2_0.csv')
credit_bureau_a_2_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_2_1.csv')

credit_bureau_b_2_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_b_2.csv')

# EDA train sets

In [61]:
def df_shape(title, df):
    print(f"{title} shape: {df.shape}")
def df_dupliactes(title, df):
    print(f"{title} duplicates: {Counter(df.is_duplicated())[1]}")
def df_duplicates_id(title, df):
    print(f"{title} duplicates id: {Counter(df.select('case_id').is_duplicated())[1]}")
def df_missing_values(title, df):
    print(f"{title} missing values: {df.null_count().sum()}")
def df_data_types(title, df):
    print(f"{title} data types: {Counter(df.dtypes)}")
def df_count_values(title, df):
  for col in df.columns:
    print(f"{title} {col} count values: {df[col].value_counts()}")
def df_null_count(title, df):
    print(f"{title} null count: {((df.null_count().sum())/len(df))*100}%")

In [13]:
base_train.sample(7)

shape: (7, 5)
┌─────────┬───────────────┬────────┬──────────┬────────┐
│ case_id ┆ date_decision ┆ MONTH  ┆ WEEK_NUM ┆ target │
│ ---     ┆ ---           ┆ ---    ┆ ---      ┆ ---    │
│ i64     ┆ str           ┆ i64    ┆ i64      ┆ i64    │
╞═════════╪═══════════════╪════════╪══════════╪════════╡
│ 1456188 ┆ 2019-07-21    ┆ 201907 ┆ 28       ┆ 0      │
│ 1611562 ┆ 2019-11-04    ┆ 201911 ┆ 43       ┆ 0      │
│ 962086  ┆ 2020-02-22    ┆ 202002 ┆ 59       ┆ 0      │
│ 2577158 ┆ 2019-05-25    ┆ 201905 ┆ 20       ┆ 0      │
│ 899994  ┆ 2019-12-15    ┆ 201912 ┆ 49       ┆ 0      │
│ 1764058 ┆ 2020-01-26    ┆ 202001 ┆ 55       ┆ 0      │
│ 1715456 ┆ 2019-12-28    ┆ 201912 ┆ 51       ┆ 0      │
└─────────┴───────────────┴────────┴──────────┴────────┘

In [14]:
static_1_train.sample(7)

shape: (7, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ i64     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ f64       ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│         ┆ f64        ┆ ---       ┆           ┆   ┆ str       ┆           ┆           ┆           │
│         ┆            ┆ str       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 889715  ┆ null       ┆ null      ┆ 2615.0    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1245390 ┆ 0.0        ┆ null      ┆ 1701.8    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 754222  ┆ null       ┆ null      ┆ 3063.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1244696 ┆ 0.0        ┆ null      ┆ 2831.0    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1278231 ┆ 0.0        ┆ null      ┆ 2589.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 141387  ┆ 0.0        ┆ 162383.81 ┆ 6119.2    ┆ … ┆ null      ┆ FO        ┆ AL        ┆ null      │
│ 2638053 ┆ 0.0        ┆ 0.0       ┆ 3654.0    ┆ … ┆ null      ┆ FO        ┆ null      ┆ 2019-11-1 │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2         │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
static_2_train.sample(7)

shape: (7, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ i64     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ f64       ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│         ┆ f64        ┆ ---       ┆           ┆   ┆ f64       ┆           ┆           ┆           │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 935426  ┆ 0.0        ┆ null      ┆ 3433.0    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1773573 ┆ 0.0        ┆ 23810.8   ┆ 3667.2    ┆ … ┆ 3663.2    ┆ FO        ┆ AL        ┆ null      │
│ 915143  ┆ null       ┆ null      ┆ 1777.8    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1899618 ┆ 0.0        ┆ 93131.664 ┆ 2404.6    ┆ … ┆ 6532.8003 ┆ FO        ┆ null      ┆ null      │
│ 1792150 ┆ 0.0        ┆ 294556.44 ┆ 4145.2    ┆ … ┆ 7293.6    ┆ FO        ┆ null      ┆ null      │
│ 975619  ┆ null       ┆ null      ┆ 3269.0    ┆ … ┆ null      ┆ FO        ┆ AL        ┆ null      │
│ 1754698 ┆ 0.0        ┆ 132321.16 ┆ 8195.4    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [16]:
static_cb_train.sample(7)

shape: (7, 53)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ assignment ┆ assignmen ┆ assignmen ┆ … ┆ riskasses ┆ riskasses ┆ secondqua ┆ thirdquar │
│ ---     ┆ date_238D  ┆ tdate_452 ┆ tdate_495 ┆   ┆ ment_302T ┆ ment_940T ┆ rter_766L ┆ ter_1082L │
│ i64     ┆ ---        ┆ 7235D     ┆ 5616D     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ str        ┆ ---       ┆ ---       ┆   ┆ str       ┆ f64       ┆ f64       ┆ f64       │
│         ┆            ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1727111 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 14.0      ┆ 12.0      │
│ 47925   ┆ null       ┆ 2020-03-1 ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.0       ┆ 1.0       │
│         ┆            ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2585933 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 8.0       ┆ 4.0       │
│ 1823186 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 4.0       ┆ 6.0       │
│ 2688073 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 16.0      ┆ 4.0       │
│ 244812  ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 3.0       ┆ 2.0       │
│ 2640714 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 4.0       ┆ 4.0       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [29]:
# Shape of train sets

# depth = 0
print("Depth = 0")
df_shape("Base", base_train)
df_shape("Static 1", static_1_train)
df_shape("Static 2", static_2_train)
df_shape("Static cb", static_cb_train)
print('=============================================================')
# depth = 1
print("Depth = 1")
df_shape("Applprev 1 0", applprev_1_0_train)
df_shape("Applprev 1 1", applprev_1_1_trian)
df_shape("Other", other_train)
df_shape("Tax registry a", tax_registry_a_train)
df_shape("Tax registry b", tax_registry_b_train)
df_shape("Tax registry c", tax_registry_c_train)
df_shape("Credit bureau a 1 0", credit_bureau_a_1_0_train)
df_shape("Credit bureau a 1 1", credit_bureau_a_1_1_train)
df_shape("Credit bureau a 1 2", credit_bureau_a_1_2_train)
df_shape("Credit bureau a 1 3", credit_bureau_a_1_3_train)
df_shape("Credit bureau b 1", credit_bureau_b_1_train)
df_shape("Deposit", deposit_trian)
df_shape("Person 1", person_1_train)
df_shape("Debitcard", debitcard_trian)
print('=============================================================')

# # depth = 2
print("Depth = 2")
df_shape("Person 2", person_2_train)
df_shape("Applprev 2", applprev_2_train)
# print('=============================================================')
df_shape("Credit bureau a 2 0", credit_bureau_a_2_0_train)
df_shape("Credit bureau a 2 1", credit_bureau_a_2_1_train)
# df_shape("Credit bureau a 2 2", credit_bureau_a_2_2_train)
# df_shape("Credit bureau a 2 3", credit_bureau_a_2_3_train)
# df_shape("Credit bureau a 2 4", credit_bureau_a_2_4_train)
# df_shape("Credit bureau a 2 5", credit_bureau_a_2_5_trian)
# df_shape("Credit bureau a 2 6", credit_bureau_a_2_6_train)
# df_shape("Credit bureau a 2 7", credit_bureau_a_2_7_train)
# df_shape("Credit bureau a 2 8", credit_bureau_a_2_8_train)
# df_shape("Credit bureau a 2 9", credit_bureau_a_2_9_train)
# df_shape("Credit bureau a 2 10", credit_bureau_a_2_10_train)
# print('=============================================================')
df_shape("Credit bureau b 2", credit_bureau_b_2_train)

Depth = 0
Base shape: (1526659, 5)
Static 1 shape: (1003757, 168)
Static 2 shape: (522902, 168)
Static cb shape: (1500476, 53)
=============================================================
Depth = 1
Applprev 1 0 shape: (3887684, 41)
Applprev 1 1 shape: (2638295, 41)
Other shape: (51109, 7)
Tax registry a shape: (3275770, 5)
Tax registry b shape: (1107933, 5)
Tax registry c shape: (3343800, 5)
Credit bureau a 1 0 shape: (4108212, 79)
Credit bureau a 1 1 shape: (6009192, 79)
Credit bureau a 1 2 shape: (3743810, 79)
Credit bureau a 1 3 shape: (2079323, 79)
Credit bureau b 1 shape: (85791, 45)
Deposit shape: (145086, 5)
Person 1 shape: (2973991, 37)
Debitcard shape: (157302, 6)
=============================================================
Depth = 2
Person 2 shape: (1643410, 11)
Applprev 2 shape: (14075487, 6)
Credit bureau a 2 0 shape: (5296031, 19)
Credit bureau a 2 1 shape: (7861809, 19)
Credit bureau b 2 shape: (1286755, 6)

In [18]:
# Data type consideration
print("Depth = 0")
df_data_types("Base", base_train)
df_data_types("Static 1", static_1_train)
df_data_types("Static 2", static_2_train)
df_data_types("Static cb", static_cb_train)
print('=========================================================================')
print("Depth = 1")
df_data_types("Applprev 1 0", applprev_1_0_train)
df_data_types("Applprev 1 1", applprev_1_1_trian)
df_data_types("Other", other_train)
df_data_types("Tax registry a", tax_registry_a_train)
df_data_types("Tax registry b", tax_registry_b_train)
df_data_types("Tax registry c", tax_registry_c_train)
df_data_types("Credit bureau a 1 0", credit_bureau_a_1_0_train)
df_data_types("Credit bureau a 1 1", credit_bureau_a_1_1_train)
df_data_types("Credit bureau a 1 2", credit_bureau_a_1_2_train)
df_data_types("Credit bureau a 1 3", credit_bureau_a_1_3_train)
df_data_types("Credit bureau b 1", credit_bureau_b_1_train)
df_data_types("Deposit", deposit_trian)
df_data_types("Person 1", person_1_train)
df_data_types("Debitcard", debitcard_trian)
print('=========================================================================')
print("Depth = 2")
df_data_types("Person 2", person_2_train)
df_data_types("Applprev 2", applprev_2_train)
df_data_types("Credit bureau a 2 0", credit_bureau_a_2_0_train)
df_data_types("Credit bureau a 2 1", credit_bureau_a_2_1_train)
# df_data_types("Credit bureau a 2 2", credit_bureau_a_2_2_train)
# df_data_types("Credit bureau a 2 3", credit_bureau_a_2_3_train)
# df_data_types("Credit bureau a 2 4", credit_bureau_a_2_4_train)
# df_data_types("Credit bureau a 2 5", credit_bureau_a_2_5_trian)
# df_data_types("Credit bureau a 2 6", credit_bureau_a_2_6_train)
# df_data_types("Credit bureau a 2 7", credit_bureau_a_2_7_train)
# df_data_types("Credit bureau a 2 8", credit_bureau_a_2_8_train)
# df_data_types("Credit bureau a 2 9", credit_bureau_a_2_9_train)
# df_data_types("Credit bureau a 2 10", credit_bureau_a_2_10_train)
df_data_types("Credit bureau b 2", credit_bureau_b_2_train)

Depth = 0
Base data types: Counter({Int64: 4, String: 1})
Static 1 data types: Counter({Float64: 100, String: 61, Boolean: 6, Int64: 1})
Static 2 data types: Counter({Float64: 123, String: 39, Boolean: 5, Int64: 1})
Static cb data types: Counter({Float64: 31, String: 21, Int64: 1})
=========================================================================
Depth = 1
Applprev 1 0 data types: Counter({String: 19, Float64: 18, Int64: 2, Boolean: 2})
Applprev 1 1 data types: Counter({String: 19, Float64: 18, Int64: 2, Boolean: 2})
Other data types: Counter({Float64: 5, Int64: 2})
Tax registry a data types: Counter({Int64: 2, String: 2, Float64: 1})
Tax registry b data types: Counter({Int64: 2, String: 2, Float64: 1})
Tax registry c data types: Counter({Int64: 2, String: 2, Float64: 1})
Credit bureau a 1 0 data types: Counter({String: 48, Float64: 29, Int64: 2})
Credit bureau a 1 1 data types: Counter({Float64: 52, String: 25, Int64: 2})
Credit bureau a 1 2 data types: Counter({Float64: 51, String: 26, Int64: 2})
Credit bureau a 1 3 data types: Counter({Float64: 53, String: 24, Int64: 2})
Credit bureau b 1 data types: Counter({Float64: 30, String: 13, Int64: 2})
Deposit data types: Counter({Int64: 2, String: 2, Float64: 1})
Person 1 data types: Counter({String: 25, Float64: 5, Boolean: 5, Int64: 2})
Debitcard data types: Counter({String: 4, Int64: 2})
=========================================================================
Depth = 2
Person 2 data types: Counter({String: 8, Int64: 3})
Applprev 2 data types: Counter({Int64: 3, String: 3})
Credit bureau a 2 0 data types: Counter({String: 11, Float64: 5, Int64: 3})
Credit bureau a 2 1 data types: Counter({String: 11, Float64: 5, Int64: 3})
Credit bureau b 2 data types: Counter({Int64: 3, Float64: 2, String: 1})

In [19]:
# Check duplicates
print("Depth = 0")
df_dupliactes("Base", base_train)
df_dupliactes("Static 1", static_1_train)
df_dupliactes("Static 2", static_2_train)
df_dupliactes("Static cb", static_cb_train)
print('=========================================================================')
print("Depth = 1")
df_dupliactes("Applprev 1 0", applprev_1_0_train)
df_dupliactes("Applprev 1 1", applprev_1_1_trian)
df_dupliactes("Other", other_train)
df_dupliactes("Tax registry a", tax_registry_a_train)
df_dupliactes("Tax registry b", tax_registry_b_train)
df_dupliactes("Tax registry c", tax_registry_c_train)
df_dupliactes("Credit bureau a 1 0", credit_bureau_a_1_0_train)
df_dupliactes("Credit bureau a 1 1", credit_bureau_a_1_1_train)
df_dupliactes("Credit bureau a 1 2", credit_bureau_a_1_2_train)
df_dupliactes("Credit bureau a 1 3", credit_bureau_a_1_3_train)
df_dupliactes("Credit bureau b 1", credit_bureau_b_1_train)
df_dupliactes("Deposit", deposit_trian)
df_dupliactes("Person 1", person_1_train)
df_dupliactes("Debitcard", debitcard_trian)
print('=========================================================================')
print("Depth = 2")
df_dupliactes("Person 2", person_2_train)
df_dupliactes("Applprev 2", applprev_2_train)
df_dupliactes("Credit bureau a 2 0", credit_bureau_a_2_0_train)
df_dupliactes("Credit bureau a 2 1", credit_bureau_a_2_1_train)
# df_dupliactes("Credit bureau a 2 2", credit_bureau_a_2_2_train)
# df_dupliactes("Credit bureau a 2 3", credit_bureau_a_2_3_train)
# df_dupliactes("Credit bureau a 2 4", credit_bureau_a_2_4_train)
# df_dupliactes("Credit bureau a 2 5", credit_bureau_a_2_5_trian)
# df_dupliactes("Credit bureau a 2 6", credit_bureau_a_2_6_train)
# df_dupliactes("Credit bureau a 2 7", credit_bureau_a_2_7_train)
# df_dupliactes("Credit bureau a 2 8", credit_bureau_a_2_8_train)
# df_dupliactes("Credit bureau a 2 9", credit_bureau_a_2_9_train)
# df_dupliactes("Credit bureau a 2 10", credit_bureau_a_2_10_train)
df_dupliactes("Credit bureau b 2", credit_bureau_b_2_train)

Depth = 0
Base duplicates: 0
Static 1 duplicates: 0
Static 2 duplicates: 0
Static cb duplicates: 0
=========================================================================
Depth = 1
Applprev 1 0 duplicates: 0
Applprev 1 1 duplicates: 0
Other duplicates: 0
Tax registry a duplicates: 0
Tax registry b duplicates: 0
Tax registry c duplicates: 0
Credit bureau a 1 0 duplicates: 0
Credit bureau a 1 1 duplicates: 0
Credit bureau a 1 2 duplicates: 0
Credit bureau a 1 3 duplicates: 0
Credit bureau b 1 duplicates: 0
Deposit duplicates: 0
Person 1 duplicates: 0
Debitcard duplicates: 0
=========================================================================
Depth = 2
Person 2 duplicates: 0
Applprev 2 duplicates: 0
Credit bureau a 2 0 duplicates: 0
Credit bureau a 2 1 duplicates: 0
Credit bureau b 2 duplicates: 0

In [20]:
# Check case_id duplicates
print("Depth = 0")
df_duplicates_id("Base", base_train)
df_duplicates_id("Static 1", static_1_train)
df_duplicates_id("Static 2", static_2_train)
df_duplicates_id("Static cb", static_cb_train)
print('=========================================================================')
print("Depth = 1")
df_duplicates_id("Applprev 1 0", applprev_1_0_train)
df_duplicates_id("Applprev 1 1", applprev_1_1_trian)
df_duplicates_id("Other", other_train)
df_duplicates_id("Tax registry a", tax_registry_a_train)
df_duplicates_id("Tax registry b", tax_registry_b_train)
df_duplicates_id("Tax registry c", tax_registry_c_train)
df_duplicates_id("Credit bureau a 1 0", credit_bureau_a_1_0_train)
df_duplicates_id("Credit bureau a 1 1", credit_bureau_a_1_1_train)
df_duplicates_id("Credit bureau a 1 2", credit_bureau_a_1_2_train)
df_duplicates_id("Credit bureau a 1 3", credit_bureau_a_1_3_train)
df_duplicates_id("Credit bureau b 1", credit_bureau_b_1_train)
df_duplicates_id("Deposit", deposit_trian)
df_duplicates_id("Person 1", person_1_train)
df_duplicates_id("Debitcard", debitcard_trian)
print('=========================================================================')
print('Depth = 2')
df_duplicates_id("Person 2", person_2_train)
df_duplicates_id("Applprev 2", applprev_2_train)
df_duplicates_id("Credit bureau a 2 0", credit_bureau_a_2_0_train)
df_duplicates_id("Credit bureau a 2 1", credit_bureau_a_2_1_train)
df_duplicates_id("Credit bureau b 2", credit_bureau_b_2_train)

Depth = 0
Base duplicates id: 0
Static 1 duplicates id: 0
Static 2 duplicates id: 0
Static cb duplicates id: 0
=========================================================================
Depth = 1
Applprev 1 0 duplicates id: 3727233
Applprev 1 1 duplicates id: 2569179
Other duplicates id: 0
Tax registry a duplicates id: 3259252
Tax registry b duplicates id: 1106411
Tax registry c duplicates id: 3324711
Credit bureau a 1 0 duplicates id: 4108056
Credit bureau a 1 1 duplicates id: 6009157
Credit bureau a 1 2 duplicates id: 3743809
Credit bureau a 1 3 duplicates id: 2079323
Credit bureau b 1 duplicates id: 76961
Deposit duplicates id: 66020
Person 1 duplicates id: 2204652
Debitcard duplicates id: 74839
=========================================================================
Depth = 2
Person 2 duplicates id: 351971
Applprev 2 duplicates id: 14036208
Credit bureau a 2 0 duplicates id: 5296031
Credit bureau a 2 1 duplicates id: 7861809
Credit bureau b 2 duplicates id: 1286332

In [64]:
# The percentage of nulls in each column in every dataset
print('Depth 0')
df_null_count("Base", base_train)
df_null_count("Static 1", static_1_train)
df_null_count("Static 2", static_2_train)
df_null_count("Static cb", static_cb_train)
print('=========================================================================')
print('Depth 1')
df_null_count("Applprev 1 0", applprev_1_0_train)
df_null_count("Applprev 1 1", applprev_1_1_trian)
df_null_count("Other", other_train)
df_null_count("Tax registry a", tax_registry_a_train)
df_null_count("Tax registry b", tax_registry_b_train)
df_null_count("Tax registry c", tax_registry_c_train)
df_null_count("Credit bureau a 1 0", credit_bureau_a_1_0_train)
df_null_count("Credit bureau a 1 1", credit_bureau_a_1_1_train)
df_null_count("Credit bureau a 1 2", credit_bureau_a_1_2_train)
df_null_count("Credit bureau a 1 3", credit_bureau_a_1_3_train)
df_null_count("Credit bureau b 1", credit_bureau_b_1_train)
df_null_count("Deposit", deposit_trian)
df_null_count("Person 1", person_1_train)
df_null_count("Debitcard", debitcard_trian)
print('=========================================================================')
print('Depth 2')
df_null_count("Person 2", person_2_train)
df_null_count("Applprev 2", applprev_2_train)
df_null_count("Credit bureau a 2 0", credit_bureau_a_2_0_train)
df_null_count("Credit bureau a 2 1", credit_bureau_a_2_1_train)
df_null_count("Credit bureau b 2", credit_bureau_b_2_train)

Depth 0
Base null count: shape: (1, 5)
┌─────────┬───────────────┬───────┬──────────┬────────┐
│ case_id ┆ date_decision ┆ MONTH ┆ WEEK_NUM ┆ target │
│ ---     ┆ ---           ┆ ---   ┆ ---      ┆ ---    │
│ f64     ┆ f64           ┆ f64   ┆ f64      ┆ f64    │
╞═════════╪═══════════════╪═══════╪══════════╪════════╡
│ 0.0     ┆ 0.0           ┆ 0.0   ┆ 0.0      ┆ 0.0    │
└─────────┴───────────────┴───────┴──────────┴────────┘%
Static 1 null count: shape: (1, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ f64     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│         ┆ f64        ┆ ---       ┆           ┆   ┆ f64       ┆           ┆           ┆           │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 29.557552  ┆ 42.724883 ┆ 0.0       ┆ … ┆ 86.182712 ┆ 0.004483  ┆ 71.255991 ┆ 88.104193 │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Static 2 null count: shape: (1, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ f64     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│         ┆ f64        ┆ ---       ┆           ┆   ┆ f64       ┆           ┆           ┆           │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 23.234182  ┆ 25.295371 ┆ 0.0       ┆ … ┆ 59.121212 ┆ 0.008797  ┆ 77.694864 ┆ 93.80993  │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Static cb null count: shape: (1, 53)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ assignment ┆ assignmen ┆ assignmen ┆ … ┆ riskasses ┆ riskasses ┆ secondqua ┆ thirdquar │
│ ---     ┆ date_238D  ┆ tdate_452 ┆ tdate_495 ┆   ┆ ment_302T ┆ ment_940T ┆ rter_766L ┆ ter_1082L │
│ f64     ┆ ---        ┆ 7235D     ┆ 5616D     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ f64        ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│         ┆            ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 90.869831  ┆ 92.337232 ┆ 95.225982 ┆ … ┆ 96.430533 ┆ 96.430466 ┆ 7.649906  ┆ 7.649906  │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
=========================================================================
Depth 1
Applprev 1 0 null count: shape: (1, 41)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpd_ ┆ annuity_8 ┆ approvald ┆ … ┆ rejectrea ┆ revolving ┆ status_21 ┆ tenor_203 │
│ ---     ┆ 943P       ┆ 53A       ┆ ate_319D  ┆   ┆ sonclient ┆ account_3 ┆ 9L        ┆ L         │
│ f64     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ _4145042M ┆ 94A       ┆ ---       ┆ ---       │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64       │
│         ┆            ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 0.057464   ┆ 4.008839  ┆ 45.426043 ┆ … ┆ 0.0       ┆ 95.970583 ┆ 0.0009    ┆ 8.04677   │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Applprev 1 1 null count: shape: (1, 41)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpd_ ┆ annuity_8 ┆ approvald ┆ … ┆ rejectrea ┆ revolving ┆ status_21 ┆ tenor_203 │
│ ---     ┆ 943P       ┆ 53A       ┆ ate_319D  ┆   ┆ sonclient ┆ account_3 ┆ 9L        ┆ L         │
│ f64     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ _4145042M ┆ 94A       ┆ ---       ┆ ---       │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64       │
│         ┆            ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 0.010082   ┆ 3.596451  ┆ 47.162012 ┆ … ┆ 0.0       ┆ 94.68979  ┆ 0.001175  ┆ 9.058388  │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Other null count: shape: (1, 7)
┌─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬────────────┐
│ case_id ┆ amtdebitincom ┆ amtdebitoutg ┆ amtdepositba ┆ amtdepositin ┆ amtdepositou ┆ num_group1 │
│ ---     ┆ ing_4809443A  ┆ oing_4809440 ┆ lance_480944 ┆ coming_48094 ┆ tgoing_48094 ┆ ---        │
│ f64     ┆ ---           ┆ A            ┆ 1A           ┆ 44A          ┆ 42A          ┆ f64        │
│         ┆ f64           ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆            │
│         ┆               ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆            │
╞═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪════════════╡
│ 0.0     ┆ 0.0           ┆ 0.0          ┆ 0.0          ┆ 0.0          ┆ 0.0          ┆ 0.0        │
└─────────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴────────────┘%
Tax registry a null count: shape: (1, 5)
┌─────────┬─────────────────┬───────────────┬────────────┬─────────────────────┐
│ case_id ┆ amount_4527230A ┆ name_4527232M ┆ num_group1 ┆ recorddate_4527225D │
│ ---     ┆ ---             ┆ ---           ┆ ---        ┆ ---                 │
│ f64     ┆ f64             ┆ f64           ┆ f64        ┆ f64                 │
╞═════════╪═════════════════╪═══════════════╪════════════╪═════════════════════╡
│ 0.0     ┆ 0.0             ┆ 0.0           ┆ 0.0        ┆ 0.0                 │
└─────────┴─────────────────┴───────────────┴────────────┴─────────────────────┘%
Tax registry b null count: shape: (1, 5)
┌─────────┬─────────────────┬────────────────────────┬───────────────┬────────────┐
│ case_id ┆ amount_4917619A ┆ deductiondate_4917603D ┆ name_4917606M ┆ num_group1 │
│ ---     ┆ ---             ┆ ---                    ┆ ---           ┆ ---        │
│ f64     ┆ f64             ┆ f64                    ┆ f64           ┆ f64        │
╞═════════╪═════════════════╪════════════════════════╪═══════════════╪════════════╡
│ 0.0     ┆ 0.0             ┆ 0.0                    ┆ 0.0           ┆ 0.0        │
└─────────┴─────────────────┴────────────────────────┴───────────────┴────────────┘%
Tax registry c null count: shape: (1, 5)
┌─────────┬───────────────────┬────────────┬───────────────┬─────────────────────┐
│ case_id ┆ employername_160M ┆ num_group1 ┆ pmtamount_36A ┆ processingdate_168D │
│ ---     ┆ ---               ┆ ---        ┆ ---           ┆ ---                 │
│ f64     ┆ f64               ┆ f64        ┆ f64           ┆ f64                 │
╞═════════╪═══════════════════╪════════════╪═══════════════╪═════════════════════╡
│ 0.0     ┆ 0.0               ┆ 0.0        ┆ 0.0           ┆ 0.0                 │
└─────────┴───────────────────┴────────────┴───────────────┴─────────────────────┘%
Credit bureau a 1 0 null count: shape: (1, 79)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ annualeffe ┆ annualeff ┆ classific ┆ … ┆ totaldebt ┆ totaldebt ┆ totalouts ┆ totalouts │
│ ---     ┆ ctiverate_ ┆ ectiverat ┆ ationofco ┆   ┆ overdueva ┆ overdueva ┆ tanddebtv ┆ tanddebtv │
│ f64     ┆ 199L       ┆ e_63L     ┆ ntr_13M   ┆   ┆ lue_178A  ┆ lue_718A  ┆ alue_39A  ┆ alue_668A │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 99.099827  ┆ 98.23921  ┆ 0.0       ┆ … ┆ 91.782946 ┆ 92.731582 ┆ 91.782946 ┆ 92.731582 │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Credit bureau a 1 1 null count: shape: (1, 79)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ annualeffe ┆ annualeff ┆ classific ┆ … ┆ totaldebt ┆ totaldebt ┆ totalouts ┆ totalouts │
│ ---     ┆ ctiverate_ ┆ ectiverat ┆ ationofco ┆   ┆ overdueva ┆ overdueva ┆ tanddebtv ┆ tanddebtv │
│ f64     ┆ 199L       ┆ e_63L     ┆ ntr_13M   ┆   ┆ lue_178A  ┆ lue_718A  ┆ alue_39A  ┆ alue_668A │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 95.385702  ┆ 98.067511 ┆ 0.0       ┆ … ┆ 91.566437 ┆ 91.746295 ┆ 91.566437 ┆ 91.746295 │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Credit bureau a 1 2 null count: shape: (1, 79)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ annualeffe ┆ annualeff ┆ classific ┆ … ┆ totaldebt ┆ totaldebt ┆ totalouts ┆ totalouts │
│ ---     ┆ ctiverate_ ┆ ectiverat ┆ ationofco ┆   ┆ overdueva ┆ overdueva ┆ tanddebtv ┆ tanddebtv │
│ f64     ┆ 199L       ┆ e_63L     ┆ ntr_13M   ┆   ┆ lue_178A  ┆ lue_718A  ┆ alue_39A  ┆ alue_668A │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 93.255694  ┆ 97.735729 ┆ 0.0       ┆ … ┆ 91.919889 ┆ 91.804579 ┆ 91.919889 ┆ 91.804579 │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Credit bureau a 1 3 null count: shape: (1, 79)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ annualeffe ┆ annualeff ┆ classific ┆ … ┆ totaldebt ┆ totaldebt ┆ totalouts ┆ totalouts │
│ ---     ┆ ctiverate_ ┆ ectiverat ┆ ationofco ┆   ┆ overdueva ┆ overdueva ┆ tanddebtv ┆ tanddebtv │
│ f64     ┆ 199L       ┆ e_63L     ┆ ntr_13M   ┆   ┆ lue_178A  ┆ lue_718A  ┆ alue_39A  ┆ alue_668A │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 92.311151  ┆ 98.172049 ┆ 0.0       ┆ … ┆ 92.394832 ┆ 91.625255 ┆ 92.394832 ┆ 91.625255 │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Credit bureau b 1 null count: shape: (1, 45)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ amount_111 ┆ classific ┆ contractd ┆ … ┆ subjectro ┆ subjectro ┆ totalamou ┆ totalamou │
│ ---     ┆ 5A         ┆ ationofco ┆ ate_551D  ┆   ┆ le_326M   ┆ le_43M    ┆ nt_503A   ┆ nt_881A   │
│ f64     ┆ ---        ┆ ntr_1114M ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ f64        ┆ ---       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 49.084403  ┆ 0.0       ┆ 4.536606  ┆ … ┆ 0.0       ┆ 0.0       ┆ 38.200977 ┆ 46.11556  │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Deposit null count: shape: (1, 5)
┌─────────┬─────────────┬──────────────────────┬────────────┬──────────────────┐
│ case_id ┆ amount_416A ┆ contractenddate_991D ┆ num_group1 ┆ openingdate_313D │
│ ---     ┆ ---         ┆ ---                  ┆ ---        ┆ ---              │
│ f64     ┆ f64         ┆ f64                  ┆ f64        ┆ f64              │
╞═════════╪═════════════╪══════════════════════╪════════════╪══════════════════╡
│ 0.0     ┆ 0.0         ┆ 54.92053             ┆ 0.0        ┆ 0.0              │
└─────────┴─────────────┴──────────────────────┴────────────┴──────────────────┘%
Person 1 null count: shape: (1, 37)
┌─────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ case_id ┆ birth_259D ┆ birthdate_ ┆ childnum_ ┆ … ┆ role_993L ┆ safeguara ┆ sex_738L  ┆ type_25L │
│ ---     ┆ ---        ┆ 87D        ┆ 185L      ┆   ┆ ---       ┆ ntyflag_4 ┆ ---       ┆ ---      │
│ f64     ┆ f64        ┆ ---        ┆ ---       ┆   ┆ f64       ┆ 11L       ┆ f64       ┆ f64      │
│         ┆            ┆ f64        ┆ f64       ┆   ┆           ┆ ---       ┆           ┆          │
│         ┆            ┆            ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.0     ┆ 48.666321  ┆ 99.162203  ┆ 99.666879 ┆ … ┆ 99.162203 ┆ 48.666388 ┆ 48.666321 ┆ 0.205683 │
└─────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘%
Debitcard null count: shape: (1, 6)
┌─────────┬──────────────────┬──────────────────┬──────────────────┬────────────┬──────────────────┐
│ case_id ┆ last180dayaverag ┆ last180dayturnov ┆ last30dayturnove ┆ num_group1 ┆ openingdate_857D │
│ ---     ┆ ebalance_704A    ┆ er_1134A         ┆ r_651A           ┆ ---        ┆ ---              │
│ f64     ┆ ---              ┆ ---              ┆ ---              ┆ f64        ┆ f64              │
│         ┆ f64              ┆ f64              ┆ f64              ┆            ┆                  │
╞═════════╪══════════════════╪══════════════════╪══════════════════╪════════════╪══════════════════╡
│ 0.0     ┆ 92.234047        ┆ 92.955589        ┆ 92.955589        ┆ 0.0        ┆ 8.080635         │
└─────────┴──────────────────┴──────────────────┴──────────────────┴────────────┴──────────────────┘%
=========================================================================
Depth 2
Person 2 null count: shape: (1, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ addres_dis ┆ addres_ro ┆ addres_zi ┆ … ┆ empls_emp ┆ num_group ┆ num_group ┆ relatedpe │
│ ---     ┆ trict_368M ┆ le_871L   ┆ p_823M    ┆   ┆ loyer_nam ┆ 1         ┆ 2         ┆ rsons_rol │
│ f64     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ e_740M    ┆ ---       ┆ ---       ┆ e_762T    │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 0.0        ┆ 95.882099 ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 98.252049 │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Applprev 2 null count: shape: (1, 6)
┌─────────┬──────────────────────┬─────────────────┬─────────────────────┬────────────┬────────────┐
│ case_id ┆ cacccardblochreas_14 ┆ conts_type_509L ┆ credacc_cards_statu ┆ num_group1 ┆ num_group2 │
│ ---     ┆ 7M                   ┆ ---             ┆ s_52L               ┆ ---        ┆ ---        │
│ f64     ┆ ---                  ┆ f64             ┆ ---                 ┆ f64        ┆ f64        │
│         ┆ f64                  ┆                 ┆ f64                 ┆            ┆            │
╞═════════╪══════════════════════╪═════════════════╪═════════════════════╪════════════╪════════════╡
│ 0.0     ┆ 0.776165             ┆ 17.00869        ┆ 97.569654           ┆ 0.0        ┆ 0.0        │
└─────────┴──────────────────────┴─────────────────┴─────────────────────┴────────────┴────────────┘%
Credit bureau a 2 0 null count: shape: (1, 19)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ collater_t ┆ collater_ ┆ collater_ ┆ … ┆ pmts_year ┆ pmts_year ┆ subjectro ┆ subjectro │
│ ---     ┆ ypofvalofg ┆ typofvalo ┆ valueofgu ┆   ┆ _1139T    ┆ _507T     ┆ les_name_ ┆ les_name_ │
│ f64     ┆ uarant_298 ┆ fguarant_ ┆ arantee_1 ┆   ┆ ---       ┆ ---       ┆ 541M      ┆ 838M      │
│         ┆ …          ┆ 407…      ┆ 124…      ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆           ┆           ┆ f64       ┆ f64       │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 0.0        ┆ 0.0       ┆ 96.168546 ┆ … ┆ 0.000434  ┆ 100.0     ┆ 0.0       ┆ 0.0       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Credit bureau a 2 1 null count: shape: (1, 19)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ collater_t ┆ collater_ ┆ collater_ ┆ … ┆ pmts_year ┆ pmts_year ┆ subjectro ┆ subjectro │
│ ---     ┆ ypofvalofg ┆ typofvalo ┆ valueofgu ┆   ┆ _1139T    ┆ _507T     ┆ les_name_ ┆ les_name_ │
│ f64     ┆ uarant_298 ┆ fguarant_ ┆ arantee_1 ┆   ┆ ---       ┆ ---       ┆ 541M      ┆ 838M      │
│         ┆ …          ┆ 407…      ┆ 124…      ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆           ┆           ┆ f64       ┆ f64       │
│         ┆ f64        ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0     ┆ 0.0        ┆ 0.0       ┆ 96.887014 ┆ … ┆ 17.393974 ┆ 76.370782 ┆ 0.0       ┆ 0.0       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘%
Credit bureau b 2 null count: shape: (1, 6)
┌─────────┬────────────┬────────────┬─────────────────┬────────────────────┬───────────────────────┐
│ case_id ┆ num_group1 ┆ num_group2 ┆ pmts_date_1107D ┆ pmts_dpdvalue_108P ┆ pmts_pmtsoverdue_635A │
│ ---     ┆ ---        ┆ ---        ┆ ---             ┆ ---                ┆ ---                   │
│ f64     ┆ f64        ┆ f64        ┆ f64             ┆ f64                ┆ f64                   │
╞═════════╪════════════╪════════════╪═════════════════╪════════════════════╪═══════════════════════╡

In [22]:
# Columns of the dataframe
print("Depth = 0")
print("Base Columns", base_train.columns)
print("Static 1 Columns", static_1_train.columns)
print("Static 2 Columns", static_2_train.columns)
print("Static cb Columns", static_cb_train.columns)
print('=========================================================================')
print("Depth = 1")
print("Applprev 1 0 Columns", applprev_1_0_train.columns)
print("Applprev 1 1 Columns", applprev_1_1_trian.columns)
print("Other Columns", other_train.columns)
print("Tax registry a Columns", tax_registry_a_train.columns)
print("Tax registry b Columns", tax_registry_b_train.columns)
print("Tax registry c Columns", tax_registry_c_train.columns)
print("Credit bureau a 1 0 Columns", credit_bureau_a_1_0_train.columns)
print("Credit bureau a 1 1 Columns", credit_bureau_a_1_1_train.columns)
print("Credit bureau a 1 2 Columns", credit_bureau_a_1_2_train.columns)
print("Credit bureau a 1 3 Columns", credit_bureau_a_1_3_train.columns)
print("Credit bureau b 1 Columns", credit_bureau_b_1_train.columns)
print("Deposit Columns", deposit_trian.columns)
print("Person 1 Columns", person_1_train.columns)
print("Debitcard Columns", debitcard_trian.columns)
print('=========================================================================')
print("Depth = 2")
print("Person 2 Columns", person_2_train.columns)
print("Applprev 2 Columns", applprev_2_train.columns)
print("Credit bureau a 2 0 Columns", credit_bureau_a_2_0_train.columns)
print("Credit bureau a 2 1 Columns", credit_bureau_a_2_1_train.columns)
print("Credit bureau b 2 Columns", credit_bureau_b_2_train.columns)

Depth = 0
Base Columns ['case_id', 'date_decision', 'MONTH', 'WEEK_NUM', 'target']
Static 1 Columns ['case_id', 'actualdpdtolerance_344P', 'amtinstpaidbefduel24m_4187115A', 'annuity_780A', 'annuitynextmonth_57A', 'applicationcnt_361L', 'applications30d_658L', 'applicationscnt_1086L', 'applicationscnt_464L', 'applicationscnt_629L', 'applicationscnt_867L', 'avgdbddpdlast24m_3658932P', 'avgdbddpdlast3m_4187120P', 'avgdbdtollast24m_4525197P', 'avgdpdtolclosure24_3658938P', 'avginstallast24m_3658937A', 'avglnamtstart24m_4525187A', 'avgmaxdpdlast9m_3716943P', 'avgoutstandbalancel6m_4187114A', 'avgpmtlast12m_4525200A', 'bankacctype_710L', 'cardtype_51L', 'clientscnt12m_3712952L', 'clientscnt3m_3712950L', 'clientscnt6m_3712949L', 'clientscnt_100L', 'clientscnt_1022L', 'clientscnt_1071L', 'clientscnt_1130L', 'clientscnt_136L', 'clientscnt_157L', 'clientscnt_257L', 'clientscnt_304L', 'clientscnt_360L', 'clientscnt_493L', 'clientscnt_533L', 'clientscnt_887L', 'clientscnt_946L', 'cntincpaycont9m_3716944L', 'cntpmts24_3658933L', 'commnoinclast6m_3546845L', 'credamount_770A', 'credtype_322L', 'currdebt_22A', 'currdebtcredtyperange_828A', 'datefirstoffer_1144D', 'datelastinstal40dpd_247D', 'datelastunpaid_3546854D', 'daysoverduetolerancedd_3976961L', 'deferredmnthsnum_166L', 'disbursedcredamount_1113A', 'disbursementtype_67L', 'downpmt_116A', 'dtlastpmtallstes_4499206D', 'eir_270L', 'equalitydataagreement_891L', 'equalityempfrom_62L', 'firstclxcampaign_1125D', 'firstdatedue_489D', 'homephncnt_628L', 'inittransactionamount_650A', 'inittransactioncode_186L', 'interestrate_311L', 'interestrategrace_34L', 'isbidproduct_1095L', 'isbidproductrequest_292L', 'isdebitcard_729L', 'lastactivateddate_801D', 'lastapplicationdate_877D', 'lastapprcommoditycat_1041M', 'lastapprcommoditytypec_5251766M', 'lastapprcredamount_781A', 'lastapprdate_640D', 'lastcancelreason_561M', 'lastdelinqdate_224D', 'lastdependentsnum_448L', 'lastotherinc_902A', 'lastotherlnsexpense_631A', 'lastrejectcommoditycat_161M', 'lastrejectcommodtypec_5251769M', 'lastrejectcredamount_222A', 'lastrejectdate_50D', 'lastrejectreason_759M', 'lastrejectreasonclient_4145040M', 'lastrepayingdate_696D', 'lastst_736L', 'maininc_215A', 'mastercontrelectronic_519L', 'mastercontrexist_109L', 'maxannuity_159A', 'maxannuity_4075009A', 'maxdbddpdlast1m_3658939P', 'maxdbddpdtollast12m_3658940P', 'maxdbddpdtollast6m_4187119P', 'maxdebt4_972A', 'maxdpdfrom6mto36m_3546853P', 'maxdpdinstldate_3546855D', 'maxdpdinstlnum_3546846P', 'maxdpdlast12m_727P', 'maxdpdlast24m_143P', 'maxdpdlast3m_392P', 'maxdpdlast6m_474P', 'maxdpdlast9m_1059P', 'maxdpdtolerance_374P', 'maxinstallast24m_3658928A', 'maxlnamtstart6m_4525199A', 'maxoutstandbalancel12m_4187113A', 'maxpmtlast3m_4525190A', 'mindbddpdlast24m_3658935P', 'mindbdtollast24m_4525191P', 'mobilephncnt_593L', 'monthsannuity_845L', 'numactivecreds_622L', 'numactivecredschannel_414L', 'numactiverelcontr_750L', 'numcontrs3months_479L', 'numincomingpmts_3546848L', 'numinstlallpaidearly3d_817L', 'numinstls_657L', 'numinstlsallpaid_934L', 'numinstlswithdpd10_728L', 'numinstlswithdpd5_4187116L', 'numinstlswithoutdpd_562L', 'numinstmatpaidtearly2d_4499204L', 'numinstpaid_4499208L', 'numinstpaidearly3d_3546850L', 'numinstpaidearly3dest_4493216L', 'numinstpaidearly5d_1087L', 'numinstpaidearly5dest_4493211L', 'numinstpaidearly5dobd_4499205L', 'numinstpaidearly_338L', 'numinstpaidearlyest_4493214L', 'numinstpaidlastcontr_4325080L', 'numinstpaidlate1d_3546852L', 'numinstregularpaid_973L', 'numinstregularpaidest_4493210L', 'numinsttopaygr_769L', 'numinsttopaygrest_4493213L', 'numinstunpaidmax_3546851L', 'numinstunpaidmaxest_4493212L', 'numnotactivated_1143L', 'numpmtchanneldd_318L', 'numrejects9m_859L', 'opencred_647L', 'paytype1st_925L', 'paytype_783L', 'payvacationpostpone_4187118D', 'pctinstlsallpaidearl3d_427L', 'pctinstlsallpaidlat10d_839L', 'pctinstlsallpaidlate1d_3546856L', 'pctinstlsallpaidlate4d_3546849L', 'pctinstlsallpaidlate6d_3546844L', 'pmtnum_254L', 'posfpd10lastmonth_333P', 'posfpd30lastmonth_3976960P', 'posfstqpd30lastmonth_3976962P', 'previouscontdistrict_112M', 'price_1097A', 'sellerplacecnt_915L', 'sellerplacescnt_216L', 'sumoutstandtotal_3546847A', 'sumoutstandtotalest_4493215A', 'totaldebt_9A', 'totalsettled_863A', 'totinstallast1m_4525188A', 'twobodfilling_608L', 'typesuite_864L', 'validfrom_1069D']
Static 2 Columns ['case_id', 'actualdpdtolerance_344P', 'amtinstpaidbefduel24m_4187115A', 'annuity_780A', 'annuitynextmonth_57A', 'applicationcnt_361L', 'applications30d_658L', 'applicationscnt_1086L', 'applicationscnt_464L', 'applicationscnt_629L', 'applicationscnt_867L', 'avgdbddpdlast24m_3658932P', 'avgdbddpdlast3m_4187120P', 'avgdbdtollast24m_4525197P', 'avgdpdtolclosure24_3658938P', 'avginstallast24m_3658937A', 'avglnamtstart24m_4525187A', 'avgmaxdpdlast9m_3716943P', 'avgoutstandbalancel6m_4187114A', 'avgpmtlast12m_4525200A', 'bankacctype_710L', 'cardtype_51L', 'clientscnt12m_3712952L', 'clientscnt3m_3712950L', 'clientscnt6m_3712949L', 'clientscnt_100L', 'clientscnt_1022L', 'clientscnt_1071L', 'clientscnt_1130L', 'clientscnt_136L', 'clientscnt_157L', 'clientscnt_257L', 'clientscnt_304L', 'clientscnt_360L', 'clientscnt_493L', 'clientscnt_533L', 'clientscnt_887L', 'clientscnt_946L', 'cntincpaycont9m_3716944L', 'cntpmts24_3658933L', 'commnoinclast6m_3546845L', 'credamount_770A', 'credtype_322L', 'currdebt_22A', 'currdebtcredtyperange_828A', 'datefirstoffer_1144D', 'datelastinstal40dpd_247D', 'datelastunpaid_3546854D', 'daysoverduetolerancedd_3976961L', 'deferredmnthsnum_166L', 'disbursedcredamount_1113A', 'disbursementtype_67L', 'downpmt_116A', 'dtlastpmtallstes_4499206D', 'eir_270L', 'equalitydataagreement_891L', 'equalityempfrom_62L', 'firstclxcampaign_1125D', 'firstdatedue_489D', 'homephncnt_628L', 'inittransactionamount_650A', 'inittransactioncode_186L', 'interestrate_311L', 'interestrategrace_34L', 'isbidproduct_1095L', 'isbidproductrequest_292L', 'isdebitcard_729L', 'lastactivateddate_801D', 'lastapplicationdate_877D', 'lastapprcommoditycat_1041M', 'lastapprcommoditytypec_5251766M', 'lastapprcredamount_781A', 'lastapprdate_640D', 'lastcancelreason_561M', 'lastdelinqdate_224D', 'lastdependentsnum_448L', 'lastotherinc_902A', 'lastotherlnsexpense_631A', 'lastrejectcommoditycat_161M', 'lastrejectcommodtypec_5251769M', 'lastrejectcredamount_222A', 'lastrejectdate_50D', 'lastrejectreason_759M', 'lastrejectreasonclient_4145040M', 'lastrepayingdate_696D', 'lastst_736L', 'maininc_215A', 'mastercontrelectronic_519L', 'mastercontrexist_109L', 'maxannuity_159A', 'maxannuity_4075009A', 'maxdbddpdlast1m_3658939P', 'maxdbddpdtollast12m_3658940P', 'maxdbddpdtollast6m_4187119P', 'maxdebt4_972A', 'maxdpdfrom6mto36m_3546853P', 'maxdpdinstldate_3546855D', 'maxdpdinstlnum_3546846P', 'maxdpdlast12m_727P', 'maxdpdlast24m_143P', 'maxdpdlast3m_392P', 'maxdpdlast6m_474P', 'maxdpdlast9m_1059P', 'maxdpdtolerance_374P', 'maxinstallast24m_3658928A', 'maxlnamtstart6m_4525199A', 'maxoutstandbalancel12m_4187113A', 'maxpmtlast3m_4525190A', 'mindbddpdlast24m_3658935P', 'mindbdtollast24m_4525191P', 'mobilephncnt_593L', 'monthsannuity_845L', 'numactivecreds_622L', 'numactivecredschannel_414L', 'numactiverelcontr_750L', 'numcontrs3months_479L', 'numincomingpmts_3546848L', 'numinstlallpaidearly3d_817L', 'numinstls_657L', 'numinstlsallpaid_934L', 'numinstlswithdpd10_728L', 'numinstlswithdpd5_4187116L', 'numinstlswithoutdpd_562L', 'numinstmatpaidtearly2d_4499204L', 'numinstpaid_4499208L', 'numinstpaidearly3d_3546850L', 'numinstpaidearly3dest_4493216L', 'numinstpaidearly5d_1087L', 'numinstpaidearly5dest_4493211L', 'numinstpaidearly5dobd_4499205L', 'numinstpaidearly_338L', 'numinstpaidearlyest_4493214L', 'numinstpaidlastcontr_4325080L', 'numinstpaidlate1d_3546852L', 'numinstregularpaid_973L', 'numinstregularpaidest_4493210L', 'numinsttopaygr_769L', 'numinsttopaygrest_4493213L', 'numinstunpaidmax_3546851L', 'numinstunpaidmaxest_4493212L', 'numnotactivated_1143L', 'numpmtchanneldd_318L', 'numrejects9m_859L', 'opencred_647L', 'paytype1st_925L', 'paytype_783L', 'payvacationpostpone_4187118D', 'pctinstlsallpaidearl3d_427L', 'pctinstlsallpaidlat10d_839L', 'pctinstlsallpaidlate1d_3546856L', 'pctinstlsallpaidlate4d_3546849L', 'pctinstlsallpaidlate6d_3546844L', 'pmtnum_254L', 'posfpd10lastmonth_333P', 'posfpd30lastmonth_3976960P', 'posfstqpd30lastmonth_3976962P', 'previouscontdistrict_112M', 'price_1097A', 'sellerplacecnt_915L', 'sellerplacescnt_216L', 'sumoutstandtotal_3546847A', 'sumoutstandtotalest_4493215A', 'totaldebt_9A', 'totalsettled_863A', 'totinstallast1m_4525188A', 'twobodfilling_608L', 'typesuite_864L', 'validfrom_1069D']
Static cb Columns ['case_id', 'assignmentdate_238D', 'assignmentdate_4527235D', 'assignmentdate_4955616D', 'birthdate_574D', 'contractssum_5085716L', 'dateofbirth_337D', 'dateofbirth_342D', 'days120_123L', 'days180_256L', 'days30_165L', 'days360_512L', 'days90_310L', 'description_5085714M', 'education_1103M', 'education_88M', 'firstquarter_103L', 'for3years_128L', 'for3years_504L', 'for3years_584L', 'formonth_118L', 'formonth_206L', 'formonth_535L', 'forquarter_1017L', 'forquarter_462L', 'forquarter_634L', 'fortoday_1092L', 'forweek_1077L', 'forweek_528L', 'forweek_601L', 'foryear_618L', 'foryear_818L', 'foryear_850L', 'fourthquarter_440L', 'maritalst_385M', 'maritalst_893M', 'numberofqueries_373L', 'pmtaverage_3A', 'pmtaverage_4527227A', 'pmtaverage_4955615A', 'pmtcount_4527229L', 'pmtcount_4955617L', 'pmtcount_693L', 'pmtscount_423L', 'pmtssum_45A', 'requesttype_4525192L', 'responsedate_1012D', 'responsedate_4527233D', 'responsedate_4917613D', 'riskassesment_302T', 'riskassesment_940T', 'secondquarter_766L', 'thirdquarter_1082L']
=========================================================================
Depth = 1
Applprev 1 0 Columns ['case_id', 'actualdpd_943P', 'annuity_853A', 'approvaldate_319D', 'byoccupationinc_3656910L', 'cancelreason_3545846M', 'childnum_21L', 'creationdate_885D', 'credacc_actualbalance_314A', 'credacc_credlmt_575A', 'credacc_maxhisbal_375A', 'credacc_minhisbal_90A', 'credacc_status_367L', 'credacc_transactions_402L', 'credamount_590A', 'credtype_587L', 'currdebt_94A', 'dateactivated_425D', 'district_544M', 'downpmt_134A', 'dtlastpmt_581D', 'dtlastpmtallstes_3545839D', 'education_1138M', 'employedfrom_700D', 'familystate_726L', 'firstnonzeroinstldate_307D', 'inittransactioncode_279L', 'isbidproduct_390L', 'isdebitcard_527L', 'mainoccupationinc_437A', 'maxdpdtolerance_577P', 'num_group1', 'outstandingdebt_522A', 'pmtnum_8L', 'postype_4733339M', 'profession_152M', 'rejectreason_755M', 'rejectreasonclient_4145042M', 'revolvingaccount_394A', 'status_219L', 'tenor_203L']
Applprev 1 1 Columns ['case_id', 'actualdpd_943P', 'annuity_853A', 'approvaldate_319D', 'byoccupationinc_3656910L', 'cancelreason_3545846M', 'childnum_21L', 'creationdate_885D', 'credacc_actualbalance_314A', 'credacc_credlmt_575A', 'credacc_maxhisbal_375A', 'credacc_minhisbal_90A', 'credacc_status_367L', 'credacc_transactions_402L', 'credamount_590A', 'credtype_587L', 'currdebt_94A', 'dateactivated_425D', 'district_544M', 'downpmt_134A', 'dtlastpmt_581D', 'dtlastpmtallstes_3545839D', 'education_1138M', 'employedfrom_700D', 'familystate_726L', 'firstnonzeroinstldate_307D', 'inittransactioncode_279L', 'isbidproduct_390L', 'isdebitcard_527L', 'mainoccupationinc_437A', 'maxdpdtolerance_577P', 'num_group1', 'outstandingdebt_522A', 'pmtnum_8L', 'postype_4733339M', 'profession_152M', 'rejectreason_755M', 'rejectreasonclient_4145042M', 'revolvingaccount_394A', 'status_219L', 'tenor_203L']
Other Columns ['case_id', 'amtdebitincoming_4809443A', 'amtdebitoutgoing_4809440A', 'amtdepositbalance_4809441A', 'amtdepositincoming_4809444A', 'amtdepositoutgoing_4809442A', 'num_group1']
Tax registry a Columns ['case_id', 'amount_4527230A', 'name_4527232M', 'num_group1', 'recorddate_4527225D']
Tax registry b Columns ['case_id', 'amount_4917619A', 'deductiondate_4917603D', 'name_4917606M', 'num_group1']
Tax registry c Columns ['case_id', 'employername_160M', 'num_group1', 'pmtamount_36A', 'processingdate_168D']
Credit bureau a 1 0 Columns ['case_id', 'annualeffectiverate_199L', 'annualeffectiverate_63L', 'classificationofcontr_13M', 'classificationofcontr_400M', 'contractst_545M', 'contractst_964M', 'contractsum_5085717L', 'credlmt_230A', 'credlmt_935A', 'dateofcredend_289D', 'dateofcredend_353D', 'dateofcredstart_181D', 'dateofcredstart_739D', 'dateofrealrepmt_138D', 'debtoutstand_525A', 'debtoverdue_47A', 'description_351M', 'dpdmax_139P', 'dpdmax_757P', 'dpdmaxdatemonth_442T', 'dpdmaxdatemonth_89T', 'dpdmaxdateyear_596T', 'dpdmaxdateyear_896T', 'financialinstitution_382M', 'financialinstitution_591M', 'instlamount_768A', 'instlamount_852A', 'interestrate_508L', 'lastupdate_1112D', 'lastupdate_388D', 'monthlyinstlamount_332A', 'monthlyinstlamount_674A', 'nominalrate_281L', 'nominalrate_498L', 'num_group1', 'numberofcontrsvalue_258L', 'numberofcontrsvalue_358L', 'numberofinstls_229L', 'numberofinstls_320L', 'numberofoutstandinstls_520L', 'numberofoutstandinstls_59L', 'numberofoverdueinstlmax_1039L', 'numberofoverdueinstlmax_1151L', 'numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D', 'numberofoverdueinstls_725L', 'numberofoverdueinstls_834L', 'outstandingamount_354A', 'outstandingamount_362A', 'overdueamount_31A', 'overdueamount_659A', 'overdueamountmax2_14A', 'overdueamountmax2_398A', 'overdueamountmax2date_1002D', 'overdueamountmax2date_1142D', 'overdueamountmax_155A', 'overdueamountmax_35A', 'overdueamountmaxdatemonth_284T', 'overdueamountmaxdatemonth_365T', 'overdueamountmaxdateyear_2T', 'overdueamountmaxdateyear_994T', 'periodicityofpmts_1102L', 'periodicityofpmts_837L', 'prolongationcount_1120L', 'prolongationcount_599L', 'purposeofcred_426M', 'purposeofcred_874M', 'refreshdate_3813885D', 'residualamount_488A', 'residualamount_856A', 'subjectrole_182M', 'subjectrole_93M', 'totalamount_6A', 'totalamount_996A', 'totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A']
Credit bureau a 1 1 Columns ['case_id', 'annualeffectiverate_199L', 'annualeffectiverate_63L', 'classificationofcontr_13M', 'classificationofcontr_400M', 'contractst_545M', 'contractst_964M', 'contractsum_5085717L', 'credlmt_230A', 'credlmt_935A', 'dateofcredend_289D', 'dateofcredend_353D', 'dateofcredstart_181D', 'dateofcredstart_739D', 'dateofrealrepmt_138D', 'debtoutstand_525A', 'debtoverdue_47A', 'description_351M', 'dpdmax_139P', 'dpdmax_757P', 'dpdmaxdatemonth_442T', 'dpdmaxdatemonth_89T', 'dpdmaxdateyear_596T', 'dpdmaxdateyear_896T', 'financialinstitution_382M', 'financialinstitution_591M', 'instlamount_768A', 'instlamount_852A', 'interestrate_508L', 'lastupdate_1112D', 'lastupdate_388D', 'monthlyinstlamount_332A', 'monthlyinstlamount_674A', 'nominalrate_281L', 'nominalrate_498L', 'num_group1', 'numberofcontrsvalue_258L', 'numberofcontrsvalue_358L', 'numberofinstls_229L', 'numberofinstls_320L', 'numberofoutstandinstls_520L', 'numberofoutstandinstls_59L', 'numberofoverdueinstlmax_1039L', 'numberofoverdueinstlmax_1151L', 'numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D', 'numberofoverdueinstls_725L', 'numberofoverdueinstls_834L', 'outstandingamount_354A', 'outstandingamount_362A', 'overdueamount_31A', 'overdueamount_659A', 'overdueamountmax2_14A', 'overdueamountmax2_398A', 'overdueamountmax2date_1002D', 'overdueamountmax2date_1142D', 'overdueamountmax_155A', 'overdueamountmax_35A', 'overdueamountmaxdatemonth_284T', 'overdueamountmaxdatemonth_365T', 'overdueamountmaxdateyear_2T', 'overdueamountmaxdateyear_994T', 'periodicityofpmts_1102L', 'periodicityofpmts_837L', 'prolongationcount_1120L', 'prolongationcount_599L', 'purposeofcred_426M', 'purposeofcred_874M', 'refreshdate_3813885D', 'residualamount_488A', 'residualamount_856A', 'subjectrole_182M', 'subjectrole_93M', 'totalamount_6A', 'totalamount_996A', 'totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A']
Credit bureau a 1 2 Columns ['case_id', 'annualeffectiverate_199L', 'annualeffectiverate_63L', 'classificationofcontr_13M', 'classificationofcontr_400M', 'contractst_545M', 'contractst_964M', 'contractsum_5085717L', 'credlmt_230A', 'credlmt_935A', 'dateofcredend_289D', 'dateofcredend_353D', 'dateofcredstart_181D', 'dateofcredstart_739D', 'dateofrealrepmt_138D', 'debtoutstand_525A', 'debtoverdue_47A', 'description_351M', 'dpdmax_139P', 'dpdmax_757P', 'dpdmaxdatemonth_442T', 'dpdmaxdatemonth_89T', 'dpdmaxdateyear_596T', 'dpdmaxdateyear_896T', 'financialinstitution_382M', 'financialinstitution_591M', 'instlamount_768A', 'instlamount_852A', 'interestrate_508L', 'lastupdate_1112D', 'lastupdate_388D', 'monthlyinstlamount_332A', 'monthlyinstlamount_674A', 'nominalrate_281L', 'nominalrate_498L', 'num_group1', 'numberofcontrsvalue_258L', 'numberofcontrsvalue_358L', 'numberofinstls_229L', 'numberofinstls_320L', 'numberofoutstandinstls_520L', 'numberofoutstandinstls_59L', 'numberofoverdueinstlmax_1039L', 'numberofoverdueinstlmax_1151L', 'numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D', 'numberofoverdueinstls_725L', 'numberofoverdueinstls_834L', 'outstandingamount_354A', 'outstandingamount_362A', 'overdueamount_31A', 'overdueamount_659A', 'overdueamountmax2_14A', 'overdueamountmax2_398A', 'overdueamountmax2date_1002D', 'overdueamountmax2date_1142D', 'overdueamountmax_155A', 'overdueamountmax_35A', 'overdueamountmaxdatemonth_284T', 'overdueamountmaxdatemonth_365T', 'overdueamountmaxdateyear_2T', 'overdueamountmaxdateyear_994T', 'periodicityofpmts_1102L', 'periodicityofpmts_837L', 'prolongationcount_1120L', 'prolongationcount_599L', 'purposeofcred_426M', 'purposeofcred_874M', 'refreshdate_3813885D', 'residualamount_488A', 'residualamount_856A', 'subjectrole_182M', 'subjectrole_93M', 'totalamount_6A', 'totalamount_996A', 'totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A']
Credit bureau a 1 3 Columns ['case_id', 'annualeffectiverate_199L', 'annualeffectiverate_63L', 'classificationofcontr_13M', 'classificationofcontr_400M', 'contractst_545M', 'contractst_964M', 'contractsum_5085717L', 'credlmt_230A', 'credlmt_935A', 'dateofcredend_289D', 'dateofcredend_353D', 'dateofcredstart_181D', 'dateofcredstart_739D', 'dateofrealrepmt_138D', 'debtoutstand_525A', 'debtoverdue_47A', 'description_351M', 'dpdmax_139P', 'dpdmax_757P', 'dpdmaxdatemonth_442T', 'dpdmaxdatemonth_89T', 'dpdmaxdateyear_596T', 'dpdmaxdateyear_896T', 'financialinstitution_382M', 'financialinstitution_591M', 'instlamount_768A', 'instlamount_852A', 'interestrate_508L', 'lastupdate_1112D', 'lastupdate_388D', 'monthlyinstlamount_332A', 'monthlyinstlamount_674A', 'nominalrate_281L', 'nominalrate_498L', 'num_group1', 'numberofcontrsvalue_258L', 'numberofcontrsvalue_358L', 'numberofinstls_229L', 'numberofinstls_320L', 'numberofoutstandinstls_520L', 'numberofoutstandinstls_59L', 'numberofoverdueinstlmax_1039L', 'numberofoverdueinstlmax_1151L', 'numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D', 'numberofoverdueinstls_725L', 'numberofoverdueinstls_834L', 'outstandingamount_354A', 'outstandingamount_362A', 'overdueamount_31A', 'overdueamount_659A', 'overdueamountmax2_14A', 'overdueamountmax2_398A', 'overdueamountmax2date_1002D', 'overdueamountmax2date_1142D', 'overdueamountmax_155A', 'overdueamountmax_35A', 'overdueamountmaxdatemonth_284T', 'overdueamountmaxdatemonth_365T', 'overdueamountmaxdateyear_2T', 'overdueamountmaxdateyear_994T', 'periodicityofpmts_1102L', 'periodicityofpmts_837L', 'prolongationcount_1120L', 'prolongationcount_599L', 'purposeofcred_426M', 'purposeofcred_874M', 'refreshdate_3813885D', 'residualamount_488A', 'residualamount_856A', 'subjectrole_182M', 'subjectrole_93M', 'totalamount_6A', 'totalamount_996A', 'totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A']

# EDA test sets

In [23]:
base_test.sample(7)

shape: (7, 4)
┌─────────┬───────────────┬────────┬──────────┐
│ case_id ┆ date_decision ┆ MONTH  ┆ WEEK_NUM │
│ ---     ┆ ---           ┆ ---    ┆ ---      │
│ i64     ┆ str           ┆ i64    ┆ i64      │
╞═════════╪═══════════════╪════════╪══════════╡
│ 57634   ┆ 2021-01-27    ┆ 202201 ┆ 100      │
│ 57633   ┆ 2022-01-25    ┆ 202201 ┆ 100      │
│ 57630   ┆ 2021-03-16    ┆ 202201 ┆ 100      │
│ 57549   ┆ 2022-01-17    ┆ 202201 ┆ 100      │
│ 57552   ┆ 2020-11-27    ┆ 202201 ┆ 100      │
│ 57543   ┆ 2021-05-14    ┆ 202201 ┆ 100      │
│ 57551   ┆ 2020-11-27    ┆ 202201 ┆ 100      │
└─────────┴───────────────┴────────┴──────────┘

In [24]:
static_1_test.sample(7)

shape: (7, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ i64     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ f64       ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│         ┆ f64        ┆ ---       ┆           ┆   ┆ f64       ┆           ┆           ┆           │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 57551   ┆ 0.0        ┆ 71036.4   ┆ 2844.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57552   ┆ 0.0        ┆ 183992.0  ┆ 6298.8003 ┆ … ┆ 18889.0   ┆ BO        ┆ null      ┆ null      │
│ 57631   ┆ 0.0        ┆ null      ┆ 2540.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57639   ┆ 0.0        ┆ 142333.14 ┆ 12599.601 ┆ … ┆ 5588.0    ┆ BO        ┆ null      ┆ null      │
│ 57630   ┆ 0.0        ┆ 0.0       ┆ 8905.0    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57637   ┆ 0.0        ┆ 43677.184 ┆ 4300.4    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57543   ┆ 0.0        ┆ 191767.36 ┆ 3674.6    ┆ … ┆ 17859.6   ┆ FO        ┆ AL        ┆ null      │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [25]:
static_2_test.sample(7)

shape: (7, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ i64     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ f64       ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│         ┆ f64        ┆ ---       ┆           ┆   ┆ f64       ┆           ┆           ┆           │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 57641   ┆ 0.0        ┆ 173284.28 ┆ 8126.2    ┆ … ┆ 13446.4   ┆ FO        ┆ null      ┆ null      │
│ 57645   ┆ 0.0        ┆ 38622.62  ┆ 11309.4   ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57633   ┆ 0.0        ┆ null      ┆ 8273.0    ┆ … ┆ null      ┆ FO        ┆ AL        ┆ null      │
│ 57647   ┆ 0.0        ┆ 116063.96 ┆ 3585.0    ┆ … ┆ 14070.0   ┆ FO        ┆ AL        ┆ null      │
│ 57634   ┆ 0.0        ┆ 39948.8   ┆ 1165.8    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57636   ┆ 0.0        ┆ 0.0       ┆ 3366.4001 ┆ … ┆ null      ┆ FO        ┆ AL        ┆ null      │
│ 57549   ┆ 0.0        ┆ 129704.4  ┆ 5742.6    ┆ … ┆ 126058.0  ┆ FO        ┆ null      ┆ null      │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [26]:
static_cb_test.sample(7)

shape: (7, 53)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ assignment ┆ assignmen ┆ assignmen ┆ … ┆ riskasses ┆ riskasses ┆ secondqua ┆ thirdquar │
│ ---     ┆ date_238D  ┆ tdate_452 ┆ tdate_495 ┆   ┆ ment_302T ┆ ment_940T ┆ rter_766L ┆ ter_1082L │
│ i64     ┆ ---        ┆ 7235D     ┆ 5616D     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ str        ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│         ┆            ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 57630   ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 4.0       ┆ 1.0       │
│ 57549   ┆ null       ┆ null      ┆ 2018-05-0 ┆ … ┆ null      ┆ null      ┆ 8.0       ┆ 2.0       │
│         ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 57633   ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 3.0       ┆ 1.0       │
│ 57632   ┆ null       ┆ null      ┆ 2015-11-2 ┆ … ┆ null      ┆ null      ┆ 1.0       ┆ 1.0       │
│         ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 57631   ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.0       ┆ 5.0       │
│ 57543   ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.0       ┆ 3.0       │
│ 57551   ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 5.0       ┆ 5.0       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [27]:
# Shape of test sets
print('Depth = 0')
df_shape("Base", base_test)
df_shape("Static 1", static_1_test)
df_shape("Static 2", static_2_test)
df_shape("Static cb", static_cb_test)
print('=============================================================')
print('Depth = 1')
df_shape("Applprev 1 0", applprev_1_0_test)
df_shape("Applprev 1 1", applprev_1_1_test)

df_shape("Other", other_test)

df_shape("Tax registry a", tax_registry_a_test)
df_shape("Tax registry b", tax_registry_b_test)
df_shape("Tax registry c", tax_registry_c_test)

df_shape("Credit bureau a 1 0", credit_bureau_a_1_0_test)
df_shape("Credit bureau a 1 1", credit_bureau_a_1_1_test)
df_shape("Credit bureau a 1 2", credit_bureau_a_1_2_test)
df_shape("Credit bureau a 1 3", credit_bureau_a_1_3_test)
df_shape("Credit bureau b 1", credit_bureau_b_1_test)

df_shape("Deposite", deposit_test)

df_shape("Person 1", person_1_test)

df_shape("Debitcard", debitcard_test)
print('=============================================================')
print('Depth = 2')
df_shape("Person 2", person_2_test)
df_shape("Applprev 2", applprev_2_test)
df_shape("Credit bureau a 2 0", credit_bureau_a_2_0_test)
df_shape("Credit bureau a 2 1", credit_bureau_a_2_1_test)
df_shape("Credit bureau b 2", credit_bureau_b_2_test)

Depth = 0
Base shape: (10, 4)
Static 1 shape: (10, 168)
Static 2 shape: (10, 168)
Static cb shape: (10, 53)
=============================================================
Depth = 1
Applprev 1 0 shape: (10, 41)
Applprev 1 1 shape: (10, 41)
Other shape: (10, 7)
Tax registry a shape: (10, 5)
Tax registry b shape: (10, 5)
Tax registry c shape: (0, 5)
Credit bureau a 1 0 shape: (10, 79)
Credit bureau a 1 1 shape: (10, 79)
Credit bureau a 1 2 shape: (10, 79)
Credit bureau a 1 3 shape: (10, 79)
Credit bureau b 1 shape: (10, 45)
Deposite shape: (10, 5)
Person 1 shape: (10, 37)
Debitcard shape: (10, 6)
=============================================================
Depth = 2
Person 2 shape: (10, 11)
Applprev 2 shape: (10, 6)
Credit bureau a 2 0 shape: (10, 19)
Credit bureau a 2 1 shape: (10, 19)
Credit bureau b 2 shape: (10, 6)

In [28]:
# Data types for test sets
print('Depth = 0')
df_data_types("Base", base_test)
df_data_types("Static 1", static_1_test)
df_data_types("Static 2", static_2_test)
df_data_types("Static cb", static_cb_test)
print('=============================================================')
print('Depth = 1')
df_data_types("Applprev 1 0", applprev_1_0_test)
df_data_types("Applprev 1 1", applprev_1_1_test)

df_data_types("Other", other_test)

df_data_types("Tax registry a", tax_registry_a_test)
df_data_types("Tax registry b", tax_registry_b_test)
df_data_types("Tax registry c", tax_registry_c_test)

df_data_types("Credit bureau a 1 0", credit_bureau_a_1_0_test)
df_data_types("Credit bureau a 1 1", credit_bureau_a_1_1_test)
df_data_types("Credit bureau a 1 2", credit_bureau_a_1_2_test)
df_data_types("Credit bureau a 1 3", credit_bureau_a_1_3_test)
df_data_types("Credit bureau b 1", credit_bureau_b_1_test)

df_data_types("Deposite", deposit_test)

df_data_types("Person 1", person_1_test)

df_data_types("Debitcard", debitcard_test)
print('=============================================================')
print('Depth = 2')
df_data_types("Person 2", person_2_test)
df_data_types("Applprev 2", applprev_2_test)
df_data_types("Credit bureau a 2 0", credit_bureau_a_2_0_test)
df_data_types("Credit bureau a 2 1", credit_bureau_a_2_1_test)
df_data_types("Credit bureau b 2", credit_bureau_b_2_test)

Depth = 0
Base data types: Counter({Int64: 3, String: 1})
Static 1 data types: Counter({Float64: 122, String: 40, Boolean: 5, Int64: 1})
Static 2 data types: Counter({Float64: 120, String: 43, Boolean: 4, Int64: 1})
Static cb data types: Counter({String: 39, Float64: 13, Int64: 1})
=============================================================
Depth = 1
Applprev 1 0 data types: Counter({String: 25, Float64: 13, Int64: 2, Boolean: 1})
Applprev 1 1 data types: Counter({String: 19, Float64: 18, Int64: 2, Boolean: 2})
Other data types: Counter({Float64: 5, Int64: 2})
Tax registry a data types: Counter({Int64: 2, String: 2, Float64: 1})
Tax registry b data types: Counter({Int64: 2, String: 2, Float64: 1})
Tax registry c data types: Counter({String: 5})
Credit bureau a 1 0 data types: Counter({Float64: 44, String: 33, Int64: 2})
Credit bureau a 1 1 data types: Counter({Float64: 51, String: 26, Int64: 2})
Credit bureau a 1 2 data types: Counter({Float64: 48, String: 29, Int64: 2})
Credit bureau a 1 3 data types: Counter({Float64: 53, String: 25, Int64: 1})
Credit bureau b 1 data types: Counter({Float64: 30, String: 13, Int64: 2})
Deposite data types: Counter({Int64: 2, String: 2, Float64: 1})
Person 1 data types: Counter({String: 25, Float64: 5, Boolean: 5, Int64: 2})
Debitcard data types: Counter({String: 4, Int64: 2})
=============================================================
Depth = 2
Person 2 data types: Counter({String: 8, Int64: 3})
Applprev 2 data types: Counter({Int64: 3, String: 3})
Credit bureau a 2 0 data types: Counter({String: 10, Float64: 6, Int64: 3})
Credit bureau a 2 1 data types: Counter({Float64: 10, String: 6, Int64: 3})
Credit bureau b 2 data types: Counter({Int64: 3, Float64: 2, String: 1})