In [1]:
import kagglehub
# You may need to re-run this cell after logging in.
kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Kaggle credentials set.
Kaggle credentials successfully validated.

In [2]:
path = kagglehub.competition_download('home-credit-credit-risk-model-stability')

Downloading to /root/.cache/kagglehub/competitions/home-credit-credit-risk-model-stability.archive...

100%|██████████| 3.14G/3.14G [00:21<00:00, 157MB/s]

Extracting files...

In [3]:
!ln -s "$path" /content/home_credit

In [ ]:
import os
from google.colab import userdata
github_token = userdata.get('github_token')
dagshub_token = userdata.get('dagshub_token')
os.environ["DAGSHUB_TOKEN"] = userdata.get("dagshub_token")
%cd /content
!git clone https://github.com/Hassan-ElBanna/Loan-Default-Prediction-Risk-Analysis.git
%cd Loan-Default-Prediction-Risk-Analysis
!git remote set-url origin https://Hassan-ElBanna:{github_token}@github.com/Hassan-ElBanna/Loan-Default-Prediction-Risk-Analysis.git
!python /content/Loan-Default-Prediction-Risk-Analysis/Scripts/setup_colab.py

In [5]:
import polars as pl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

# Train sets

In [6]:
# Train sets

# depth = 0
base_train = pl.read_csv('/content/home_credit/csv_files/train/train_base.csv')
static_1_train = pl.read_csv('/content/home_credit/csv_files/train/train_static_0_0.csv')
static_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_static_0_1.csv')
static_cb_train = pl.read_csv('/content/home_credit/csv_files/train/train_static_cb_0.csv')

In [7]:
# depth = 1
applprev_1_0_train = pl.read_csv('/content/home_credit/csv_files/train/train_applprev_1_0.csv')
applprev_1_1_trian = pl.read_csv('/content/home_credit/csv_files/train/train_applprev_1_1.csv')

other_train = pl.read_csv('/content/home_credit/csv_files/train/train_other_1.csv')

tax_registry_a_train = pl.read_csv('/content/home_credit/csv_files/train/train_tax_registry_a_1.csv')
tax_registry_b_train = pl.read_csv('/content/home_credit/csv_files/train/train_tax_registry_b_1.csv')
tax_registry_c_train = pl.read_csv('/content/home_credit/csv_files/train/train_tax_registry_c_1.csv')

credit_bureau_a_1_0_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_1_0.csv')
credit_bureau_a_1_1_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_1_1.csv')
credit_bureau_a_1_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_1_2.csv')
credit_bureau_a_1_3_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_1_3.csv')
credit_bureau_b_1_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_b_1.csv')

deposit_trian = pl.read_csv('/content/home_credit/csv_files/train/train_deposit_1.csv')

person_1_train = pl.read_csv('/content/home_credit/csv_files/train/train_person_1.csv')

debitcard_trian = pl.read_csv('/content/home_credit/csv_files/train/train_debitcard_1.csv')

In [8]:
# depth = 2
person_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_person_2.csv')

applprev_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_applprev_2.csv')

credit_bureau_a_2_0_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_0.csv')
credit_bureau_a_2_1_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_1.csv')
# credit_bureau_a_2_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_2.csv')
# credit_bureau_a_2_3_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_3.csv')
# credit_bureau_a_2_4_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_4.csv')
# credit_bureau_a_2_5_trian = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_5.csv')
# credit_bureau_a_2_6_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_6.csv')
# credit_bureau_a_2_7_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_7.csv')
# credit_bureau_a_2_8_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_8.csv')
# credit_bureau_a_2_9_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_9.csv')
# credit_bureau_a_2_10_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_a_2_10.csv')

credit_bureau_b_2_train = pl.read_csv('/content/home_credit/csv_files/train/train_credit_bureau_b_2.csv')

# Test sets

In [9]:
# test sets

# depth = 0
base_test = pl.read_csv('/content/home_credit/csv_files/test/test_base.csv')
static_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_static_0_0.csv')
static_2_test = pl.read_csv('/content/home_credit/csv_files/test/test_static_0_1.csv')
static_cb_test = pl.read_csv('/content/home_credit/csv_files/test/test_static_cb_0.csv')

In [10]:
# depth = 1
applprev_1_0_test = pl.read_csv('/content/home_credit/csv_files/test/test_applprev_1_0.csv')
applprev_1_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_applprev_1_1.csv')

other_test = pl.read_csv('/content/home_credit/csv_files/test/test_other_1.csv')

tax_registry_a_test = pl.read_csv('/content/home_credit/csv_files/test/test_tax_registry_a_1.csv')
tax_registry_b_test = pl.read_csv('/content/home_credit/csv_files/test/test_tax_registry_b_1.csv')
tax_registry_c_test = pl.read_csv('/content/home_credit/csv_files/test/test_tax_registry_c_1.csv')

credit_bureau_a_1_0_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_1_0.csv')
credit_bureau_a_1_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_1_1.csv')
credit_bureau_a_1_2_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_1_2.csv')
credit_bureau_a_1_3_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_1_3.csv')
credit_bureau_b_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_b_1.csv')

deposit_test = pl.read_csv('/content/home_credit/csv_files/test/test_deposit_1.csv')

person_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_person_1.csv')

debitcard_test = pl.read_csv('/content/home_credit/csv_files/test/test_debitcard_1.csv')

In [11]:
# depth = 2
person_2_test = pl.read_csv('/content/home_credit/csv_files/test/test_person_2.csv')

applprev_2_test = pl.read_csv('/content/home_credit/csv_files/test/test_applprev_2.csv')

credit_bureau_a_2_0_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_2_0.csv')
credit_bureau_a_2_1_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_a_2_1.csv')

credit_bureau_b_2_test = pl.read_csv('/content/home_credit/csv_files/test/test_credit_bureau_b_2.csv')

# EDA train sets

In [12]:
def df_shape(title, df):
    print(f"{title} shape: {df.shape}")
def df_dupliactes(title, df):
    print(f"{title} duplicates: {Counter(df.is_duplicated())[1]}")
def df_duplicates_id(title, df):
    print(f"{title} duplicates id: {Counter(df.select('case_id').is_duplicated())[1]}")
def df_missing_values(title, df):
    print(f"{title} missing values: {df.null_count().sum()}")
def df_data_types(title, df):
    print(f"{title} data types: {Counter(df.dtypes)}")

In [13]:
base_train.sample(7)

shape: (7, 5)
┌─────────┬───────────────┬────────┬──────────┬────────┐
│ case_id ┆ date_decision ┆ MONTH  ┆ WEEK_NUM ┆ target │
│ ---     ┆ ---           ┆ ---    ┆ ---      ┆ ---    │
│ i64     ┆ str           ┆ i64    ┆ i64      ┆ i64    │
╞═════════╪═══════════════╪════════╪══════════╪════════╡
│ 240807  ┆ 2020-07-28    ┆ 202007 ┆ 82       ┆ 0      │
│ 212216  ┆ 2020-03-03    ┆ 202003 ┆ 61       ┆ 0      │
│ 1286476 ┆ 2019-02-18    ┆ 201902 ┆ 6        ┆ 0      │
│ 1504718 ┆ 2019-08-25    ┆ 201908 ┆ 33       ┆ 0      │
│ 27306   ┆ 2019-08-20    ┆ 201908 ┆ 33       ┆ 0      │
│ 1317267 ┆ 2019-03-22    ┆ 201903 ┆ 11       ┆ 0      │
│ 1511328 ┆ 2019-08-30    ┆ 201908 ┆ 34       ┆ 0      │
└─────────┴───────────────┴────────┴──────────┴────────┘

In [14]:
static_1_train.sample(7)

shape: (7, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ i64     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ f64       ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│         ┆ f64        ┆ ---       ┆           ┆   ┆ str       ┆           ┆           ┆           │
│         ┆            ┆ str       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1639493 ┆ 0.0        ┆ 71006.28  ┆ 2992.4001 ┆ … ┆ 21130.084 ┆ FO        ┆ null      ┆ null      │
│ 1275332 ┆ 0.0        ┆ null      ┆ 4220.4    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1391801 ┆ 0.0        ┆ 5492.654  ┆ 6054.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1634684 ┆ 0.0        ┆ 2822.936  ┆ 1243.2001 ┆ … ┆ 17.336    ┆ FO        ┆ null      ┆ null      │
│ 1406984 ┆ 0.0        ┆ 179495.97 ┆ 2416.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1537571 ┆ 0.0        ┆ 37824.6   ┆ 4028.2    ┆ … ┆ 4727.2    ┆ FO        ┆ null      ┆ null      │
│ 849475  ┆ null       ┆ null      ┆ 7138.6    ┆ … ┆ null      ┆ FO        ┆ AL        ┆ null      │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
static_2_train.sample(7)

shape: (7, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ i64     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ f64       ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│         ┆ f64        ┆ ---       ┆           ┆   ┆ f64       ┆           ┆           ┆           │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 917886  ┆ null       ┆ null      ┆ 6479.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1852125 ┆ 0.0        ┆ 123812.80 ┆ 2581.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│         ┆            ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 950963  ┆ null       ┆ null      ┆ 24516.0   ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 954509  ┆ null       ┆ null      ┆ 2627.2    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1920127 ┆ 0.0        ┆ 9634.0    ┆ 2091.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 1022346 ┆ null       ┆ null      ┆ 5598.8003 ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 2657069 ┆ 0.0        ┆ 56594.2   ┆ 11119.0   ┆ … ┆ null      ┆ FO        ┆ null      ┆ 2019-10-1 │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6         │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [16]:
static_cb_train.sample(7)

shape: (7, 53)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ assignment ┆ assignmen ┆ assignmen ┆ … ┆ riskasses ┆ riskasses ┆ secondqua ┆ thirdquar │
│ ---     ┆ date_238D  ┆ tdate_452 ┆ tdate_495 ┆   ┆ ment_302T ┆ ment_940T ┆ rter_766L ┆ ter_1082L │
│ i64     ┆ ---        ┆ 7235D     ┆ 5616D     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ str        ┆ ---       ┆ ---       ┆   ┆ str       ┆ f64       ┆ f64       ┆ f64       │
│         ┆            ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 836209  ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ 0.0       │
│ 1668131 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.0       ┆ 3.0       │
│ 1615119 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 1.0       ┆ 3.0       │
│ 9351    ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1284238 ┆ null       ┆ null      ┆ null      ┆ … ┆ 2% - 3%   ┆ 1.0759689 ┆ null      ┆ null      │
│ 1802892 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ 2.0       │
│ 1401696 ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 3.0       ┆ 1.0       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
# Shape of train sets

# depth = 0
print("Depth = 0")
df_shape("Base", base_train)
df_shape("Static 1", static_1_train)
df_shape("Static 2", static_2_train)
df_shape("Static cb", static_cb_train)
print('=============================================================')
# depth = 1
print("Depth = 1")
df_shape("Applprev 1 0", applprev_1_0_train)
df_shape("Applprev 1 1", applprev_1_1_trian)
print('=============================================================')
df_shape("Other", other_train)
print('=============================================================')
df_shape("Tax registry a", tax_registry_a_train)
df_shape("Tax registry b", tax_registry_b_train)
df_shape("Tax registry c", tax_registry_c_train)
print('=============================================================')
df_shape("Credit bureau a 1 0", credit_bureau_a_1_0_train)
df_shape("Credit bureau a 1 1", credit_bureau_a_1_1_train)
df_shape("Credit bureau a 1 2", credit_bureau_a_1_2_train)
df_shape("Credit bureau a 1 3", credit_bureau_a_1_3_train)
df_shape("Credit bureau b 1", credit_bureau_b_1_train)
print('=============================================================')
df_shape("Deposit", deposit_trian)
print('=============================================================')
df_shape("Person 1", person_1_train)
print('=============================================================')
df_shape("Debitcard", debitcard_trian)
print('=============================================================')

# # depth = 2
print("Depth = 2")
df_shape("Person 2", person_2_train)
df_shape("Applprev 2", applprev_2_train)
# print('=============================================================')
df_shape("Credit bureau a 2 0", credit_bureau_a_2_0_train)
df_shape("Credit bureau a 2 1", credit_bureau_a_2_1_train)
# df_shape("Credit bureau a 2 2", credit_bureau_a_2_2_train)
# df_shape("Credit bureau a 2 3", credit_bureau_a_2_3_train)
# df_shape("Credit bureau a 2 4", credit_bureau_a_2_4_train)
# df_shape("Credit bureau a 2 5", credit_bureau_a_2_5_trian)
# df_shape("Credit bureau a 2 6", credit_bureau_a_2_6_train)
# df_shape("Credit bureau a 2 7", credit_bureau_a_2_7_train)
# df_shape("Credit bureau a 2 8", credit_bureau_a_2_8_train)
# df_shape("Credit bureau a 2 9", credit_bureau_a_2_9_train)
# df_shape("Credit bureau a 2 10", credit_bureau_a_2_10_train)
# print('=============================================================')
df_shape("Credit bureau b 2", credit_bureau_b_2_train)

Depth = 0
Base shape: (1526659, 5)
Static 1 shape: (1003757, 168)
Static 2 shape: (522902, 168)
Static cb shape: (1500476, 53)
=============================================================
Depth = 1
Applprev 1 0 shape: (3887684, 41)
Applprev 1 1 shape: (2638295, 41)
=============================================================
Other shape: (51109, 7)
=============================================================
Tax registry a shape: (3275770, 5)
Tax registry b shape: (1107933, 5)
Tax registry c shape: (3343800, 5)
=============================================================
Credit bureau a 1 0 shape: (4108212, 79)
Credit bureau a 1 1 shape: (6009192, 79)
Credit bureau a 1 2 shape: (3743810, 79)
Credit bureau a 1 3 shape: (2079323, 79)
Credit bureau b 1 shape: (85791, 45)
=============================================================
Deposit shape: (145086, 5)
=============================================================
Person 1 shape: (2973991, 37)
=============================================================
Debitcard shape: (157302, 6)
=============================================================
Depth = 2
Person 2 shape: (1643410, 11)
Applprev 2 shape: (14075487, 6)
Credit bureau a 2 0 shape: (5296031, 19)
Credit bureau a 2 1 shape: (7861809, 19)
Credit bureau b 2 shape: (1286755, 6)

In [18]:
# Data type consideration
print("Depth = 0")
df_data_types("Base", base_train)
df_data_types("Static 1", static_1_train)
df_data_types("Static 2", static_2_train)
df_data_types("Static cb", static_cb_train)
print('=========================================================================')
print("Depth = 1")
df_data_types("Applprev 1 0", applprev_1_0_train)
df_data_types("Applprev 1 1", applprev_1_1_trian)
df_data_types("Other", other_train)
df_data_types("Tax registry a", tax_registry_a_train)
df_data_types("Tax registry b", tax_registry_b_train)
df_data_types("Tax registry c", tax_registry_c_train)
df_data_types("Credit bureau a 1 0", credit_bureau_a_1_0_train)
df_data_types("Credit bureau a 1 1", credit_bureau_a_1_1_train)
df_data_types("Credit bureau a 1 2", credit_bureau_a_1_2_train)
df_data_types("Credit bureau a 1 3", credit_bureau_a_1_3_train)
df_data_types("Credit bureau b 1", credit_bureau_b_1_train)
df_data_types("Deposit", deposit_trian)
df_data_types("Person 1", person_1_train)
df_data_types("Debitcard", debitcard_trian)
print('=========================================================================')
print("Depth = 2")
df_data_types("Person 2", person_2_train)
df_data_types("Applprev 2", applprev_2_train)
df_data_types("Credit bureau a 2 0", credit_bureau_a_2_0_train)
df_data_types("Credit bureau a 2 1", credit_bureau_a_2_1_train)
# df_data_types("Credit bureau a 2 2", credit_bureau_a_2_2_train)
# df_data_types("Credit bureau a 2 3", credit_bureau_a_2_3_train)
# df_data_types("Credit bureau a 2 4", credit_bureau_a_2_4_train)
# df_data_types("Credit bureau a 2 5", credit_bureau_a_2_5_trian)
# df_data_types("Credit bureau a 2 6", credit_bureau_a_2_6_train)
# df_data_types("Credit bureau a 2 7", credit_bureau_a_2_7_train)
# df_data_types("Credit bureau a 2 8", credit_bureau_a_2_8_train)
# df_data_types("Credit bureau a 2 9", credit_bureau_a_2_9_train)
# df_data_types("Credit bureau a 2 10", credit_bureau_a_2_10_train)
df_data_types("Credit bureau b 2", credit_bureau_b_2_train)

Depth = 0
Base data types: Counter({Int64: 4, String: 1})
Static 1 data types: Counter({Float64: 100, String: 61, Boolean: 6, Int64: 1})
Static 2 data types: Counter({Float64: 123, String: 39, Boolean: 5, Int64: 1})
Static cb data types: Counter({Float64: 31, String: 21, Int64: 1})
=========================================================================
Depth = 1
Applprev 1 0 data types: Counter({String: 19, Float64: 18, Int64: 2, Boolean: 2})
Applprev 1 1 data types: Counter({String: 19, Float64: 18, Int64: 2, Boolean: 2})
Other data types: Counter({Float64: 5, Int64: 2})
Tax registry a data types: Counter({Int64: 2, String: 2, Float64: 1})
Tax registry b data types: Counter({Int64: 2, String: 2, Float64: 1})
Tax registry c data types: Counter({Int64: 2, String: 2, Float64: 1})
Credit bureau a 1 0 data types: Counter({String: 48, Float64: 29, Int64: 2})
Credit bureau a 1 1 data types: Counter({Float64: 52, String: 25, Int64: 2})
Credit bureau a 1 2 data types: Counter({Float64: 51, String: 26, Int64: 2})
Credit bureau a 1 3 data types: Counter({Float64: 53, String: 24, Int64: 2})
Credit bureau b 1 data types: Counter({Float64: 30, String: 13, Int64: 2})
Deposit data types: Counter({Int64: 2, String: 2, Float64: 1})
Person 1 data types: Counter({String: 25, Float64: 5, Boolean: 5, Int64: 2})
Debitcard data types: Counter({String: 4, Int64: 2})
=========================================================================
Depth = 2
Person 2 data types: Counter({String: 8, Int64: 3})
Applprev 2 data types: Counter({Int64: 3, String: 3})
Credit bureau a 2 0 data types: Counter({String: 11, Float64: 5, Int64: 3})
Credit bureau a 2 1 data types: Counter({String: 11, Float64: 5, Int64: 3})
Credit bureau b 2 data types: Counter({Int64: 3, Float64: 2, String: 1})

In [19]:
# Check duplicates
print("Depth = 0")
df_dupliactes("Base", base_train)
df_dupliactes("Static 1", static_1_train)
df_dupliactes("Static 2", static_2_train)
df_dupliactes("Static cb", static_cb_train)
print('=========================================================================')
print("Depth = 1")
df_dupliactes("Applprev 1 0", applprev_1_0_train)
df_dupliactes("Applprev 1 1", applprev_1_1_trian)
df_dupliactes("Other", other_train)
df_dupliactes("Tax registry a", tax_registry_a_train)
df_dupliactes("Tax registry b", tax_registry_b_train)
df_dupliactes("Tax registry c", tax_registry_c_train)
df_dupliactes("Credit bureau a 1 0", credit_bureau_a_1_0_train)
df_dupliactes("Credit bureau a 1 1", credit_bureau_a_1_1_train)
df_dupliactes("Credit bureau a 1 2", credit_bureau_a_1_2_train)
df_dupliactes("Credit bureau a 1 3", credit_bureau_a_1_3_train)
df_dupliactes("Credit bureau b 1", credit_bureau_b_1_train)
df_dupliactes("Deposit", deposit_trian)
df_dupliactes("Person 1", person_1_train)
df_dupliactes("Debitcard", debitcard_trian)
print('=========================================================================')
print("Depth = 2")
df_dupliactes("Person 2", person_2_train)
df_dupliactes("Applprev 2", applprev_2_train)
df_dupliactes("Credit bureau a 2 0", credit_bureau_a_2_0_train)
df_dupliactes("Credit bureau a 2 1", credit_bureau_a_2_1_train)
# df_dupliactes("Credit bureau a 2 2", credit_bureau_a_2_2_train)
# df_dupliactes("Credit bureau a 2 3", credit_bureau_a_2_3_train)
# df_dupliactes("Credit bureau a 2 4", credit_bureau_a_2_4_train)
# df_dupliactes("Credit bureau a 2 5", credit_bureau_a_2_5_trian)
# df_dupliactes("Credit bureau a 2 6", credit_bureau_a_2_6_train)
# df_dupliactes("Credit bureau a 2 7", credit_bureau_a_2_7_train)
# df_dupliactes("Credit bureau a 2 8", credit_bureau_a_2_8_train)
# df_dupliactes("Credit bureau a 2 9", credit_bureau_a_2_9_train)
# df_dupliactes("Credit bureau a 2 10", credit_bureau_a_2_10_train)
df_dupliactes("Credit bureau b 2", credit_bureau_b_2_train)

Depth = 0
Base duplicates: 0
Static 1 duplicates: 0
Static 2 duplicates: 0
Static cb duplicates: 0
=========================================================================
Depth = 1
Applprev 1 0 duplicates: 0
Applprev 1 1 duplicates: 0
Other duplicates: 0
Tax registry a duplicates: 0
Tax registry b duplicates: 0
Tax registry c duplicates: 0
Credit bureau a 1 0 duplicates: 0
Credit bureau a 1 1 duplicates: 0
Credit bureau a 1 2 duplicates: 0
Credit bureau a 1 3 duplicates: 0
Credit bureau b 1 duplicates: 0
Deposit duplicates: 0
Person 1 duplicates: 0
Debitcard duplicates: 0
=========================================================================
Depth = 2
Person 2 duplicates: 0
Applprev 2 duplicates: 0
Credit bureau a 2 0 duplicates: 0
Credit bureau a 2 1 duplicates: 0
Credit bureau b 2 duplicates: 0

In [20]:
# Check case_id duplicates
print("Depth = 0")
df_duplicates_id("Base", base_train)
df_duplicates_id("Static 1", static_1_train)
df_duplicates_id("Static 2", static_2_train)
df_duplicates_id("Static cb", static_cb_train)
print('=========================================================================')
print("Depth = 1")
df_duplicates_id("Applprev 1 0", applprev_1_0_train)
df_duplicates_id("Applprev 1 1", applprev_1_1_trian)
df_duplicates_id("Other", other_train)
df_duplicates_id("Tax registry a", tax_registry_a_train)
df_duplicates_id("Tax registry b", tax_registry_b_train)
df_duplicates_id("Tax registry c", tax_registry_c_train)
df_duplicates_id("Credit bureau a 1 0", credit_bureau_a_1_0_train)
df_duplicates_id("Credit bureau a 1 1", credit_bureau_a_1_1_train)
df_duplicates_id("Credit bureau a 1 2", credit_bureau_a_1_2_train)
df_duplicates_id("Credit bureau a 1 3", credit_bureau_a_1_3_train)
df_duplicates_id("Credit bureau b 1", credit_bureau_b_1_train)
df_duplicates_id("Deposit", deposit_trian)
df_duplicates_id("Person 1", person_1_train)
df_duplicates_id("Debitcard", debitcard_trian)
print('=========================================================================')
print('Depth = 2')
df_duplicates_id("Person 2", person_2_train)
df_duplicates_id("Applprev 2", applprev_2_train)
df_duplicates_id("Credit bureau a 2 0", credit_bureau_a_2_0_train)
df_duplicates_id("Credit bureau a 2 1", credit_bureau_a_2_1_train)
df_duplicates_id("Credit bureau b 2", credit_bureau_b_2_train)

Depth = 0
Base duplicates id: 0
Static 1 duplicates id: 0
Static 2 duplicates id: 0
Static cb duplicates id: 0
=========================================================================
Depth = 1
Applprev 1 0 duplicates id: 3727233
Applprev 1 1 duplicates id: 2569179
Other duplicates id: 0
Tax registry a duplicates id: 3259252
Tax registry b duplicates id: 1106411
Tax registry c duplicates id: 3324711
Credit bureau a 1 0 duplicates id: 4108056
Credit bureau a 1 1 duplicates id: 6009157
Credit bureau a 1 2 duplicates id: 3743809
Credit bureau a 1 3 duplicates id: 2079323
Credit bureau b 1 duplicates id: 76961
Deposit duplicates id: 66020
Person 1 duplicates id: 2204652
Debitcard duplicates id: 74839
=========================================================================
Depth = 2
Person 2 duplicates id: 351971
Applprev 2 duplicates id: 14036208
Credit bureau a 2 0 duplicates id: 5296031
Credit bureau a 2 1 duplicates id: 7861809
Credit bureau b 2 duplicates id: 1286332

In [21]:
# Check missing values
print("Depth = 0")
df_missing_values("Base", base_train)
df_missing_values("Static 1", static_1_train)
df_missing_values("Static 2", static_2_train)
df_missing_values("Static cb", static_cb_train)
print('=========================================================================')
print('Depth = 1')
df_missing_values("Applprev 1 0", applprev_1_0_train)
df_missing_values("Applprev 1 1", applprev_1_1_trian)
df_missing_values("Other", other_train)
df_missing_values("Tax registry a", tax_registry_a_train)
df_missing_values("Tax registry b", tax_registry_b_train)
df_missing_values("Tax registry c", tax_registry_c_train)
df_missing_values("Credit bureau a 1 0", credit_bureau_a_1_0_train)
df_missing_values("Credit bureau a 1 1", credit_bureau_a_1_1_train)
df_missing_values("Credit bureau a 1 2", credit_bureau_a_1_2_train)
df_missing_values("Credit bureau a 1 3", credit_bureau_a_1_3_train)
df_missing_values("Credit bureau b 1", credit_bureau_b_1_train)
df_missing_values("Deposit", deposit_trian)
df_missing_values("Person 1", person_1_train)
df_missing_values("Debitcard", debitcard_trian)
print('=========================================================================')
print('Depth = 2')
df_missing_values("Person 2", person_2_train)
df_missing_values("Applprev 2", applprev_2_train)
df_missing_values("Credit bureau a 2 0", credit_bureau_a_2_0_train)
df_missing_values("Credit bureau a 2 1", credit_bureau_a_2_1_train)
df_missing_values("Credit bureau b 2", credit_bureau_b_2_train)

Depth = 0
Base missing values: shape: (1, 5)
┌─────────┬───────────────┬───────┬──────────┬────────┐
│ case_id ┆ date_decision ┆ MONTH ┆ WEEK_NUM ┆ target │
│ ---     ┆ ---           ┆ ---   ┆ ---      ┆ ---    │
│ u32     ┆ u32           ┆ u32   ┆ u32      ┆ u32    │
╞═════════╪═══════════════╪═══════╪══════════╪════════╡
│ 0       ┆ 0             ┆ 0     ┆ 0        ┆ 0      │
└─────────┴───────────────┴───────┴──────────┴────────┘
Static 1 missing values: shape: (1, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ u32     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ u32       ┆   ┆ ---       ┆ u32       ┆ u32       ┆ u32       │
│         ┆ u32        ┆ ---       ┆           ┆   ┆ u32       ┆           ┆           ┆           │
│         ┆            ┆ u32       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 296686     ┆ 428854    ┆ 0         ┆ … ┆ 865065    ┆ 45        ┆ 715237    ┆ 884352    │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Static 2 missing values: shape: (1, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ u32     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ u32       ┆   ┆ ---       ┆ u32       ┆ u32       ┆ u32       │
│         ┆ u32        ┆ ---       ┆           ┆   ┆ u32       ┆           ┆           ┆           │
│         ┆            ┆ u32       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 121492     ┆ 132270    ┆ 0         ┆ … ┆ 309146    ┆ 46        ┆ 406268    ┆ 490534    │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Static cb missing values: shape: (1, 53)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ assignment ┆ assignmen ┆ assignmen ┆ … ┆ riskasses ┆ riskasses ┆ secondqua ┆ thirdquar │
│ ---     ┆ date_238D  ┆ tdate_452 ┆ tdate_495 ┆   ┆ ment_302T ┆ ment_940T ┆ rter_766L ┆ ter_1082L │
│ u32     ┆ ---        ┆ 7235D     ┆ 5616D     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ u32        ┆ ---       ┆ ---       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
│         ┆            ┆ u32       ┆ u32       ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 1363480    ┆ 1385498   ┆ 1428843   ┆ … ┆ 1446917   ┆ 1446916   ┆ 114785    ┆ 114785    │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
=========================================================================
Depth = 1
Applprev 1 0 missing values: shape: (1, 41)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpd_ ┆ annuity_8 ┆ approvald ┆ … ┆ rejectrea ┆ revolving ┆ status_21 ┆ tenor_203 │
│ ---     ┆ 943P       ┆ 53A       ┆ ate_319D  ┆   ┆ sonclient ┆ account_3 ┆ 9L        ┆ L         │
│ u32     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ _4145042M ┆ 94A       ┆ ---       ┆ ---       │
│         ┆ u32        ┆ u32       ┆ u32       ┆   ┆ ---       ┆ ---       ┆ u32       ┆ u32       │
│         ┆            ┆           ┆           ┆   ┆ u32       ┆ u32       ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 2234       ┆ 155851    ┆ 1766021   ┆ … ┆ 0         ┆ 3731033   ┆ 35        ┆ 312833    │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Applprev 1 1 missing values: shape: (1, 41)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpd_ ┆ annuity_8 ┆ approvald ┆ … ┆ rejectrea ┆ revolving ┆ status_21 ┆ tenor_203 │
│ ---     ┆ 943P       ┆ 53A       ┆ ate_319D  ┆   ┆ sonclient ┆ account_3 ┆ 9L        ┆ L         │
│ u32     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ _4145042M ┆ 94A       ┆ ---       ┆ ---       │
│         ┆ u32        ┆ u32       ┆ u32       ┆   ┆ ---       ┆ ---       ┆ u32       ┆ u32       │
│         ┆            ┆           ┆           ┆   ┆ u32       ┆ u32       ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 266        ┆ 94885     ┆ 1244273   ┆ … ┆ 0         ┆ 2498196   ┆ 31        ┆ 238987    │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Other missing values: shape: (1, 7)
┌─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬────────────┐
│ case_id ┆ amtdebitincom ┆ amtdebitoutg ┆ amtdepositba ┆ amtdepositin ┆ amtdepositou ┆ num_group1 │
│ ---     ┆ ing_4809443A  ┆ oing_4809440 ┆ lance_480944 ┆ coming_48094 ┆ tgoing_48094 ┆ ---        │
│ u32     ┆ ---           ┆ A            ┆ 1A           ┆ 44A          ┆ 42A          ┆ u32        │
│         ┆ u32           ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆            │
│         ┆               ┆ u32          ┆ u32          ┆ u32          ┆ u32          ┆            │
╞═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪════════════╡
│ 0       ┆ 0             ┆ 0            ┆ 0            ┆ 0            ┆ 0            ┆ 0          │
└─────────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴────────────┘
Tax registry a missing values: shape: (1, 5)
┌─────────┬─────────────────┬───────────────┬────────────┬─────────────────────┐
│ case_id ┆ amount_4527230A ┆ name_4527232M ┆ num_group1 ┆ recorddate_4527225D │
│ ---     ┆ ---             ┆ ---           ┆ ---        ┆ ---                 │
│ u32     ┆ u32             ┆ u32           ┆ u32        ┆ u32                 │
╞═════════╪═════════════════╪═══════════════╪════════════╪═════════════════════╡
│ 0       ┆ 0               ┆ 0             ┆ 0          ┆ 0                   │
└─────────┴─────────────────┴───────────────┴────────────┴─────────────────────┘
Tax registry b missing values: shape: (1, 5)
┌─────────┬─────────────────┬────────────────────────┬───────────────┬────────────┐
│ case_id ┆ amount_4917619A ┆ deductiondate_4917603D ┆ name_4917606M ┆ num_group1 │
│ ---     ┆ ---             ┆ ---                    ┆ ---           ┆ ---        │
│ u32     ┆ u32             ┆ u32                    ┆ u32           ┆ u32        │
╞═════════╪═════════════════╪════════════════════════╪═══════════════╪════════════╡
│ 0       ┆ 0               ┆ 0                      ┆ 0             ┆ 0          │
└─────────┴─────────────────┴────────────────────────┴───────────────┴────────────┘
Tax registry c missing values: shape: (1, 5)
┌─────────┬───────────────────┬────────────┬───────────────┬─────────────────────┐
│ case_id ┆ employername_160M ┆ num_group1 ┆ pmtamount_36A ┆ processingdate_168D │
│ ---     ┆ ---               ┆ ---        ┆ ---           ┆ ---                 │
│ u32     ┆ u32               ┆ u32        ┆ u32           ┆ u32                 │
╞═════════╪═══════════════════╪════════════╪═══════════════╪═════════════════════╡
│ 0       ┆ 0                 ┆ 0          ┆ 0             ┆ 0                   │
└─────────┴───────────────────┴────────────┴───────────────┴─────────────────────┘
Credit bureau a 1 0 missing values: shape: (1, 79)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ annualeffe ┆ annualeff ┆ classific ┆ … ┆ totaldebt ┆ totaldebt ┆ totalouts ┆ totalouts │
│ ---     ┆ ctiverate_ ┆ ectiverat ┆ ationofco ┆   ┆ overdueva ┆ overdueva ┆ tanddebtv ┆ tanddebtv │
│ u32     ┆ 199L       ┆ e_63L     ┆ ntr_13M   ┆   ┆ lue_178A  ┆ lue_718A  ┆ alue_39A  ┆ alue_668A │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 4071231    ┆ 4035875   ┆ 0         ┆ … ┆ 3770638   ┆ 3809610   ┆ 3770638   ┆ 3809610   │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Credit bureau a 1 1 missing values: shape: (1, 79)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ annualeffe ┆ annualeff ┆ classific ┆ … ┆ totaldebt ┆ totaldebt ┆ totalouts ┆ totalouts │
│ ---     ┆ ctiverate_ ┆ ectiverat ┆ ationofco ┆   ┆ overdueva ┆ overdueva ┆ tanddebtv ┆ tanddebtv │
│ u32     ┆ 199L       ┆ e_63L     ┆ ntr_13M   ┆   ┆ lue_178A  ┆ lue_718A  ┆ alue_39A  ┆ alue_668A │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 5731910    ┆ 5893065   ┆ 0         ┆ … ┆ 5502403   ┆ 5513211   ┆ 5502403   ┆ 5513211   │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Credit bureau a 1 2 missing values: shape: (1, 79)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ annualeffe ┆ annualeff ┆ classific ┆ … ┆ totaldebt ┆ totaldebt ┆ totalouts ┆ totalouts │
│ ---     ┆ ctiverate_ ┆ ectiverat ┆ ationofco ┆   ┆ overdueva ┆ overdueva ┆ tanddebtv ┆ tanddebtv │
│ u32     ┆ 199L       ┆ e_63L     ┆ ntr_13M   ┆   ┆ lue_178A  ┆ lue_718A  ┆ alue_39A  ┆ alue_668A │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 3491316    ┆ 3659040   ┆ 0         ┆ … ┆ 3441306   ┆ 3436989   ┆ 3441306   ┆ 3436989   │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Credit bureau a 1 3 missing values: shape: (1, 79)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ annualeffe ┆ annualeff ┆ classific ┆ … ┆ totaldebt ┆ totaldebt ┆ totalouts ┆ totalouts │
│ ---     ┆ ctiverate_ ┆ ectiverat ┆ ationofco ┆   ┆ overdueva ┆ overdueva ┆ tanddebtv ┆ tanddebtv │
│ u32     ┆ 199L       ┆ e_63L     ┆ ntr_13M   ┆   ┆ lue_178A  ┆ lue_718A  ┆ alue_39A  ┆ alue_668A │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ u32        ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 1919447    ┆ 2041314   ┆ 0         ┆ … ┆ 1921187   ┆ 1905185   ┆ 1921187   ┆ 1905185   │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Credit bureau b 1 missing values: shape: (1, 45)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ amount_111 ┆ classific ┆ contractd ┆ … ┆ subjectro ┆ subjectro ┆ totalamou ┆ totalamou │
│ ---     ┆ 5A         ┆ ationofco ┆ ate_551D  ┆   ┆ le_326M   ┆ le_43M    ┆ nt_503A   ┆ nt_881A   │
│ u32     ┆ ---        ┆ ntr_1114M ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ u32        ┆ ---       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
│         ┆            ┆ u32       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 42110      ┆ 0         ┆ 3892      ┆ … ┆ 0         ┆ 0         ┆ 32773     ┆ 39563     │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Deposit missing values: shape: (1, 5)
┌─────────┬─────────────┬──────────────────────┬────────────┬──────────────────┐
│ case_id ┆ amount_416A ┆ contractenddate_991D ┆ num_group1 ┆ openingdate_313D │
│ ---     ┆ ---         ┆ ---                  ┆ ---        ┆ ---              │
│ u32     ┆ u32         ┆ u32                  ┆ u32        ┆ u32              │
╞═════════╪═════════════╪══════════════════════╪════════════╪══════════════════╡
│ 0       ┆ 0           ┆ 79682                ┆ 0          ┆ 0                │
└─────────┴─────────────┴──────────────────────┴────────────┴──────────────────┘
Person 1 missing values: shape: (1, 37)
┌─────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────────┬──────────┐
│ case_id ┆ birth_259D ┆ birthdate_ ┆ childnum_1 ┆ … ┆ role_993L ┆ safeguara ┆ sex_738L ┆ type_25L │
│ ---     ┆ ---        ┆ 87D        ┆ 85L        ┆   ┆ ---       ┆ ntyflag_4 ┆ ---      ┆ ---      │
│ u32     ┆ u32        ┆ ---        ┆ ---        ┆   ┆ u32       ┆ 11L       ┆ u32      ┆ u32      │
│         ┆            ┆ u32        ┆ u32        ┆   ┆           ┆ ---       ┆          ┆          │
│         ┆            ┆            ┆            ┆   ┆           ┆ u32       ┆          ┆          │
╞═════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════════╪══════════╡
│ 0       ┆ 1447332    ┆ 2949075    ┆ 2964084    ┆ … ┆ 2949075   ┆ 1447334   ┆ 1447332  ┆ 6117     │
└─────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────────┴──────────┘
Debitcard missing values: shape: (1, 6)
┌─────────┬──────────────────┬──────────────────┬──────────────────┬────────────┬──────────────────┐
│ case_id ┆ last180dayaverag ┆ last180dayturnov ┆ last30dayturnove ┆ num_group1 ┆ openingdate_857D │
│ ---     ┆ ebalance_704A    ┆ er_1134A         ┆ r_651A           ┆ ---        ┆ ---              │
│ u32     ┆ ---              ┆ ---              ┆ ---              ┆ u32        ┆ u32              │
│         ┆ u32              ┆ u32              ┆ u32              ┆            ┆                  │
╞═════════╪══════════════════╪══════════════════╪══════════════════╪════════════╪══════════════════╡
│ 0       ┆ 145086           ┆ 146221           ┆ 146221           ┆ 0          ┆ 12711            │
└─────────┴──────────────────┴──────────────────┴──────────────────┴────────────┴──────────────────┘
=========================================================================
Depth = 2
Person 2 missing values: shape: (1, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ addres_dis ┆ addres_ro ┆ addres_zi ┆ … ┆ empls_emp ┆ num_group ┆ num_group ┆ relatedpe │
│ ---     ┆ trict_368M ┆ le_871L   ┆ p_823M    ┆   ┆ loyer_nam ┆ 1         ┆ 2         ┆ rsons_rol │
│ u32     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ e_740M    ┆ ---       ┆ ---       ┆ e_762T    │
│         ┆ u32        ┆ u32       ┆ u32       ┆   ┆ ---       ┆ u32       ┆ u32       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆ u32       ┆           ┆           ┆ u32       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 0          ┆ 1575736   ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1614684   │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Applprev 2 missing values: shape: (1, 6)
┌─────────┬──────────────────────┬─────────────────┬─────────────────────┬────────────┬────────────┐
│ case_id ┆ cacccardblochreas_14 ┆ conts_type_509L ┆ credacc_cards_statu ┆ num_group1 ┆ num_group2 │
│ ---     ┆ 7M                   ┆ ---             ┆ s_52L               ┆ ---        ┆ ---        │
│ u32     ┆ ---                  ┆ u32             ┆ ---                 ┆ u32        ┆ u32        │
│         ┆ u32                  ┆                 ┆ u32                 ┆            ┆            │
╞═════════╪══════════════════════╪═════════════════╪═════════════════════╪════════════╪════════════╡
│ 0       ┆ 109249               ┆ 2394056         ┆ 13733404            ┆ 0          ┆ 0          │
└─────────┴──────────────────────┴─────────────────┴─────────────────────┴────────────┴────────────┘
Credit bureau a 2 0 missing values: shape: (1, 19)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ collater_t ┆ collater_ ┆ collater_ ┆ … ┆ pmts_year ┆ pmts_year ┆ subjectro ┆ subjectro │
│ ---     ┆ ypofvalofg ┆ typofvalo ┆ valueofgu ┆   ┆ _1139T    ┆ _507T     ┆ les_name_ ┆ les_name_ │
│ u32     ┆ uarant_298 ┆ fguarant_ ┆ arantee_1 ┆   ┆ ---       ┆ ---       ┆ 541M      ┆ 838M      │
│         ┆ …          ┆ 407…      ┆ 124…      ┆   ┆ u32       ┆ u32       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆           ┆           ┆ u32       ┆ u32       │
│         ┆ u32        ┆ u32       ┆ u32       ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 0          ┆ 0         ┆ 5093116   ┆ … ┆ 23        ┆ 5296031   ┆ 0         ┆ 0         │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Credit bureau a 2 1 missing values: shape: (1, 19)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ collater_t ┆ collater_ ┆ collater_ ┆ … ┆ pmts_year ┆ pmts_year ┆ subjectro ┆ subjectro │
│ ---     ┆ ypofvalofg ┆ typofvalo ┆ valueofgu ┆   ┆ _1139T    ┆ _507T     ┆ les_name_ ┆ les_name_ │
│ u32     ┆ uarant_298 ┆ fguarant_ ┆ arantee_1 ┆   ┆ ---       ┆ ---       ┆ 541M      ┆ 838M      │
│         ┆ …          ┆ 407…      ┆ 124…      ┆   ┆ u32       ┆ u32       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ ---       ┆ ---       ┆   ┆           ┆           ┆ u32       ┆ u32       │
│         ┆ u32        ┆ u32       ┆ u32       ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 0          ┆ 0         ┆ 7617072   ┆ … ┆ 1367481   ┆ 6004125   ┆ 0         ┆ 0         │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
Credit bureau b 2 missing values: shape: (1, 6)
┌─────────┬────────────┬────────────┬─────────────────┬────────────────────┬───────────────────────┐
│ case_id ┆ num_group1 ┆ num_group2 ┆ pmts_date_1107D ┆ pmts_dpdvalue_108P ┆ pmts_pmtsoverdue_635A │
│ ---     ┆ ---        ┆ ---        ┆ ---             ┆ ---                ┆ ---                   │
│ u32     ┆ u32        ┆ u32        ┆ u32             ┆ u32                ┆ u32                   │

In [28]:
# Columns of the dataframe
print("Depth = 0")
print("Base Columns", base_train.columns)
print("Static 1 Columns", static_1_train.columns)
print("Static 2 Columns", static_2_train.columns)
print("Static cb Columns", static_cb_train.columns)
print('=========================================================================')
print("Depth = 1")
print("Applprev 1 0 Columns", applprev_1_0_train.columns)
print("Applprev 1 1 Columns", applprev_1_1_trian.columns)
print("Other Columns", other_train.columns)
print("Tax registry a Columns", tax_registry_a_train.columns)
print("Tax registry b Columns", tax_registry_b_train.columns)
print("Tax registry c Columns", tax_registry_c_train.columns)
print("Credit bureau a 1 0 Columns", credit_bureau_a_1_0_train.columns)
print("Credit bureau a 1 1 Columns", credit_bureau_a_1_1_train.columns)
print("Credit bureau a 1 2 Columns", credit_bureau_a_1_2_train.columns)
print("Credit bureau a 1 3 Columns", credit_bureau_a_1_3_train.columns)
print("Credit bureau b 1 Columns", credit_bureau_b_1_train.columns)
print("Deposit Columns", deposit_trian.columns)
print("Person 1 Columns", person_1_train.columns)
print("Debitcard Columns", debitcard_trian.columns)
print('=========================================================================')
print("Depth = 2")
print("Person 2 Columns", person_2_train.columns)
print("Applprev 2 Columns", applprev_2_train.columns)
print("Credit bureau a 2 0 Columns", credit_bureau_a_2_0_train.columns)
print("Credit bureau a 2 1 Columns", credit_bureau_a_2_1_train.columns)
print("Credit bureau b 2 Columns", credit_bureau_b_2_train.columns)

Depth = 0
Base Columns ['case_id', 'date_decision', 'MONTH', 'WEEK_NUM', 'target']
Static 1 Columns ['case_id', 'actualdpdtolerance_344P', 'amtinstpaidbefduel24m_4187115A', 'annuity_780A', 'annuitynextmonth_57A', 'applicationcnt_361L', 'applications30d_658L', 'applicationscnt_1086L', 'applicationscnt_464L', 'applicationscnt_629L', 'applicationscnt_867L', 'avgdbddpdlast24m_3658932P', 'avgdbddpdlast3m_4187120P', 'avgdbdtollast24m_4525197P', 'avgdpdtolclosure24_3658938P', 'avginstallast24m_3658937A', 'avglnamtstart24m_4525187A', 'avgmaxdpdlast9m_3716943P', 'avgoutstandbalancel6m_4187114A', 'avgpmtlast12m_4525200A', 'bankacctype_710L', 'cardtype_51L', 'clientscnt12m_3712952L', 'clientscnt3m_3712950L', 'clientscnt6m_3712949L', 'clientscnt_100L', 'clientscnt_1022L', 'clientscnt_1071L', 'clientscnt_1130L', 'clientscnt_136L', 'clientscnt_157L', 'clientscnt_257L', 'clientscnt_304L', 'clientscnt_360L', 'clientscnt_493L', 'clientscnt_533L', 'clientscnt_887L', 'clientscnt_946L', 'cntincpaycont9m_3716944L', 'cntpmts24_3658933L', 'commnoinclast6m_3546845L', 'credamount_770A', 'credtype_322L', 'currdebt_22A', 'currdebtcredtyperange_828A', 'datefirstoffer_1144D', 'datelastinstal40dpd_247D', 'datelastunpaid_3546854D', 'daysoverduetolerancedd_3976961L', 'deferredmnthsnum_166L', 'disbursedcredamount_1113A', 'disbursementtype_67L', 'downpmt_116A', 'dtlastpmtallstes_4499206D', 'eir_270L', 'equalitydataagreement_891L', 'equalityempfrom_62L', 'firstclxcampaign_1125D', 'firstdatedue_489D', 'homephncnt_628L', 'inittransactionamount_650A', 'inittransactioncode_186L', 'interestrate_311L', 'interestrategrace_34L', 'isbidproduct_1095L', 'isbidproductrequest_292L', 'isdebitcard_729L', 'lastactivateddate_801D', 'lastapplicationdate_877D', 'lastapprcommoditycat_1041M', 'lastapprcommoditytypec_5251766M', 'lastapprcredamount_781A', 'lastapprdate_640D', 'lastcancelreason_561M', 'lastdelinqdate_224D', 'lastdependentsnum_448L', 'lastotherinc_902A', 'lastotherlnsexpense_631A', 'lastrejectcommoditycat_161M', 'lastrejectcommodtypec_5251769M', 'lastrejectcredamount_222A', 'lastrejectdate_50D', 'lastrejectreason_759M', 'lastrejectreasonclient_4145040M', 'lastrepayingdate_696D', 'lastst_736L', 'maininc_215A', 'mastercontrelectronic_519L', 'mastercontrexist_109L', 'maxannuity_159A', 'maxannuity_4075009A', 'maxdbddpdlast1m_3658939P', 'maxdbddpdtollast12m_3658940P', 'maxdbddpdtollast6m_4187119P', 'maxdebt4_972A', 'maxdpdfrom6mto36m_3546853P', 'maxdpdinstldate_3546855D', 'maxdpdinstlnum_3546846P', 'maxdpdlast12m_727P', 'maxdpdlast24m_143P', 'maxdpdlast3m_392P', 'maxdpdlast6m_474P', 'maxdpdlast9m_1059P', 'maxdpdtolerance_374P', 'maxinstallast24m_3658928A', 'maxlnamtstart6m_4525199A', 'maxoutstandbalancel12m_4187113A', 'maxpmtlast3m_4525190A', 'mindbddpdlast24m_3658935P', 'mindbdtollast24m_4525191P', 'mobilephncnt_593L', 'monthsannuity_845L', 'numactivecreds_622L', 'numactivecredschannel_414L', 'numactiverelcontr_750L', 'numcontrs3months_479L', 'numincomingpmts_3546848L', 'numinstlallpaidearly3d_817L', 'numinstls_657L', 'numinstlsallpaid_934L', 'numinstlswithdpd10_728L', 'numinstlswithdpd5_4187116L', 'numinstlswithoutdpd_562L', 'numinstmatpaidtearly2d_4499204L', 'numinstpaid_4499208L', 'numinstpaidearly3d_3546850L', 'numinstpaidearly3dest_4493216L', 'numinstpaidearly5d_1087L', 'numinstpaidearly5dest_4493211L', 'numinstpaidearly5dobd_4499205L', 'numinstpaidearly_338L', 'numinstpaidearlyest_4493214L', 'numinstpaidlastcontr_4325080L', 'numinstpaidlate1d_3546852L', 'numinstregularpaid_973L', 'numinstregularpaidest_4493210L', 'numinsttopaygr_769L', 'numinsttopaygrest_4493213L', 'numinstunpaidmax_3546851L', 'numinstunpaidmaxest_4493212L', 'numnotactivated_1143L', 'numpmtchanneldd_318L', 'numrejects9m_859L', 'opencred_647L', 'paytype1st_925L', 'paytype_783L', 'payvacationpostpone_4187118D', 'pctinstlsallpaidearl3d_427L', 'pctinstlsallpaidlat10d_839L', 'pctinstlsallpaidlate1d_3546856L', 'pctinstlsallpaidlate4d_3546849L', 'pctinstlsallpaidlate6d_3546844L', 'pmtnum_254L', 'posfpd10lastmonth_333P', 'posfpd30lastmonth_3976960P', 'posfstqpd30lastmonth_3976962P', 'previouscontdistrict_112M', 'price_1097A', 'sellerplacecnt_915L', 'sellerplacescnt_216L', 'sumoutstandtotal_3546847A', 'sumoutstandtotalest_4493215A', 'totaldebt_9A', 'totalsettled_863A', 'totinstallast1m_4525188A', 'twobodfilling_608L', 'typesuite_864L', 'validfrom_1069D']
Static 2 Columns ['case_id', 'actualdpdtolerance_344P', 'amtinstpaidbefduel24m_4187115A', 'annuity_780A', 'annuitynextmonth_57A', 'applicationcnt_361L', 'applications30d_658L', 'applicationscnt_1086L', 'applicationscnt_464L', 'applicationscnt_629L', 'applicationscnt_867L', 'avgdbddpdlast24m_3658932P', 'avgdbddpdlast3m_4187120P', 'avgdbdtollast24m_4525197P', 'avgdpdtolclosure24_3658938P', 'avginstallast24m_3658937A', 'avglnamtstart24m_4525187A', 'avgmaxdpdlast9m_3716943P', 'avgoutstandbalancel6m_4187114A', 'avgpmtlast12m_4525200A', 'bankacctype_710L', 'cardtype_51L', 'clientscnt12m_3712952L', 'clientscnt3m_3712950L', 'clientscnt6m_3712949L', 'clientscnt_100L', 'clientscnt_1022L', 'clientscnt_1071L', 'clientscnt_1130L', 'clientscnt_136L', 'clientscnt_157L', 'clientscnt_257L', 'clientscnt_304L', 'clientscnt_360L', 'clientscnt_493L', 'clientscnt_533L', 'clientscnt_887L', 'clientscnt_946L', 'cntincpaycont9m_3716944L', 'cntpmts24_3658933L', 'commnoinclast6m_3546845L', 'credamount_770A', 'credtype_322L', 'currdebt_22A', 'currdebtcredtyperange_828A', 'datefirstoffer_1144D', 'datelastinstal40dpd_247D', 'datelastunpaid_3546854D', 'daysoverduetolerancedd_3976961L', 'deferredmnthsnum_166L', 'disbursedcredamount_1113A', 'disbursementtype_67L', 'downpmt_116A', 'dtlastpmtallstes_4499206D', 'eir_270L', 'equalitydataagreement_891L', 'equalityempfrom_62L', 'firstclxcampaign_1125D', 'firstdatedue_489D', 'homephncnt_628L', 'inittransactionamount_650A', 'inittransactioncode_186L', 'interestrate_311L', 'interestrategrace_34L', 'isbidproduct_1095L', 'isbidproductrequest_292L', 'isdebitcard_729L', 'lastactivateddate_801D', 'lastapplicationdate_877D', 'lastapprcommoditycat_1041M', 'lastapprcommoditytypec_5251766M', 'lastapprcredamount_781A', 'lastapprdate_640D', 'lastcancelreason_561M', 'lastdelinqdate_224D', 'lastdependentsnum_448L', 'lastotherinc_902A', 'lastotherlnsexpense_631A', 'lastrejectcommoditycat_161M', 'lastrejectcommodtypec_5251769M', 'lastrejectcredamount_222A', 'lastrejectdate_50D', 'lastrejectreason_759M', 'lastrejectreasonclient_4145040M', 'lastrepayingdate_696D', 'lastst_736L', 'maininc_215A', 'mastercontrelectronic_519L', 'mastercontrexist_109L', 'maxannuity_159A', 'maxannuity_4075009A', 'maxdbddpdlast1m_3658939P', 'maxdbddpdtollast12m_3658940P', 'maxdbddpdtollast6m_4187119P', 'maxdebt4_972A', 'maxdpdfrom6mto36m_3546853P', 'maxdpdinstldate_3546855D', 'maxdpdinstlnum_3546846P', 'maxdpdlast12m_727P', 'maxdpdlast24m_143P', 'maxdpdlast3m_392P', 'maxdpdlast6m_474P', 'maxdpdlast9m_1059P', 'maxdpdtolerance_374P', 'maxinstallast24m_3658928A', 'maxlnamtstart6m_4525199A', 'maxoutstandbalancel12m_4187113A', 'maxpmtlast3m_4525190A', 'mindbddpdlast24m_3658935P', 'mindbdtollast24m_4525191P', 'mobilephncnt_593L', 'monthsannuity_845L', 'numactivecreds_622L', 'numactivecredschannel_414L', 'numactiverelcontr_750L', 'numcontrs3months_479L', 'numincomingpmts_3546848L', 'numinstlallpaidearly3d_817L', 'numinstls_657L', 'numinstlsallpaid_934L', 'numinstlswithdpd10_728L', 'numinstlswithdpd5_4187116L', 'numinstlswithoutdpd_562L', 'numinstmatpaidtearly2d_4499204L', 'numinstpaid_4499208L', 'numinstpaidearly3d_3546850L', 'numinstpaidearly3dest_4493216L', 'numinstpaidearly5d_1087L', 'numinstpaidearly5dest_4493211L', 'numinstpaidearly5dobd_4499205L', 'numinstpaidearly_338L', 'numinstpaidearlyest_4493214L', 'numinstpaidlastcontr_4325080L', 'numinstpaidlate1d_3546852L', 'numinstregularpaid_973L', 'numinstregularpaidest_4493210L', 'numinsttopaygr_769L', 'numinsttopaygrest_4493213L', 'numinstunpaidmax_3546851L', 'numinstunpaidmaxest_4493212L', 'numnotactivated_1143L', 'numpmtchanneldd_318L', 'numrejects9m_859L', 'opencred_647L', 'paytype1st_925L', 'paytype_783L', 'payvacationpostpone_4187118D', 'pctinstlsallpaidearl3d_427L', 'pctinstlsallpaidlat10d_839L', 'pctinstlsallpaidlate1d_3546856L', 'pctinstlsallpaidlate4d_3546849L', 'pctinstlsallpaidlate6d_3546844L', 'pmtnum_254L', 'posfpd10lastmonth_333P', 'posfpd30lastmonth_3976960P', 'posfstqpd30lastmonth_3976962P', 'previouscontdistrict_112M', 'price_1097A', 'sellerplacecnt_915L', 'sellerplacescnt_216L', 'sumoutstandtotal_3546847A', 'sumoutstandtotalest_4493215A', 'totaldebt_9A', 'totalsettled_863A', 'totinstallast1m_4525188A', 'twobodfilling_608L', 'typesuite_864L', 'validfrom_1069D']
Static cb Columns ['case_id', 'assignmentdate_238D', 'assignmentdate_4527235D', 'assignmentdate_4955616D', 'birthdate_574D', 'contractssum_5085716L', 'dateofbirth_337D', 'dateofbirth_342D', 'days120_123L', 'days180_256L', 'days30_165L', 'days360_512L', 'days90_310L', 'description_5085714M', 'education_1103M', 'education_88M', 'firstquarter_103L', 'for3years_128L', 'for3years_504L', 'for3years_584L', 'formonth_118L', 'formonth_206L', 'formonth_535L', 'forquarter_1017L', 'forquarter_462L', 'forquarter_634L', 'fortoday_1092L', 'forweek_1077L', 'forweek_528L', 'forweek_601L', 'foryear_618L', 'foryear_818L', 'foryear_850L', 'fourthquarter_440L', 'maritalst_385M', 'maritalst_893M', 'numberofqueries_373L', 'pmtaverage_3A', 'pmtaverage_4527227A', 'pmtaverage_4955615A', 'pmtcount_4527229L', 'pmtcount_4955617L', 'pmtcount_693L', 'pmtscount_423L', 'pmtssum_45A', 'requesttype_4525192L', 'responsedate_1012D', 'responsedate_4527233D', 'responsedate_4917613D', 'riskassesment_302T', 'riskassesment_940T', 'secondquarter_766L', 'thirdquarter_1082L']
=========================================================================
Depth = 1
Applprev 1 0 Columns ['case_id', 'actualdpd_943P', 'annuity_853A', 'approvaldate_319D', 'byoccupationinc_3656910L', 'cancelreason_3545846M', 'childnum_21L', 'creationdate_885D', 'credacc_actualbalance_314A', 'credacc_credlmt_575A', 'credacc_maxhisbal_375A', 'credacc_minhisbal_90A', 'credacc_status_367L', 'credacc_transactions_402L', 'credamount_590A', 'credtype_587L', 'currdebt_94A', 'dateactivated_425D', 'district_544M', 'downpmt_134A', 'dtlastpmt_581D', 'dtlastpmtallstes_3545839D', 'education_1138M', 'employedfrom_700D', 'familystate_726L', 'firstnonzeroinstldate_307D', 'inittransactioncode_279L', 'isbidproduct_390L', 'isdebitcard_527L', 'mainoccupationinc_437A', 'maxdpdtolerance_577P', 'num_group1', 'outstandingdebt_522A', 'pmtnum_8L', 'postype_4733339M', 'profession_152M', 'rejectreason_755M', 'rejectreasonclient_4145042M', 'revolvingaccount_394A', 'status_219L', 'tenor_203L']
Applprev 1 1 Columns ['case_id', 'actualdpd_943P', 'annuity_853A', 'approvaldate_319D', 'byoccupationinc_3656910L', 'cancelreason_3545846M', 'childnum_21L', 'creationdate_885D', 'credacc_actualbalance_314A', 'credacc_credlmt_575A', 'credacc_maxhisbal_375A', 'credacc_minhisbal_90A', 'credacc_status_367L', 'credacc_transactions_402L', 'credamount_590A', 'credtype_587L', 'currdebt_94A', 'dateactivated_425D', 'district_544M', 'downpmt_134A', 'dtlastpmt_581D', 'dtlastpmtallstes_3545839D', 'education_1138M', 'employedfrom_700D', 'familystate_726L', 'firstnonzeroinstldate_307D', 'inittransactioncode_279L', 'isbidproduct_390L', 'isdebitcard_527L', 'mainoccupationinc_437A', 'maxdpdtolerance_577P', 'num_group1', 'outstandingdebt_522A', 'pmtnum_8L', 'postype_4733339M', 'profession_152M', 'rejectreason_755M', 'rejectreasonclient_4145042M', 'revolvingaccount_394A', 'status_219L', 'tenor_203L']
Other Columns ['case_id', 'amtdebitincoming_4809443A', 'amtdebitoutgoing_4809440A', 'amtdepositbalance_4809441A', 'amtdepositincoming_4809444A', 'amtdepositoutgoing_4809442A', 'num_group1']
Tax registry a Columns ['case_id', 'amount_4527230A', 'name_4527232M', 'num_group1', 'recorddate_4527225D']
Tax registry b Columns ['case_id', 'amount_4917619A', 'deductiondate_4917603D', 'name_4917606M', 'num_group1']
Tax registry c Columns ['case_id', 'employername_160M', 'num_group1', 'pmtamount_36A', 'processingdate_168D']
Credit bureau a 1 0 Columns ['case_id', 'annualeffectiverate_199L', 'annualeffectiverate_63L', 'classificationofcontr_13M', 'classificationofcontr_400M', 'contractst_545M', 'contractst_964M', 'contractsum_5085717L', 'credlmt_230A', 'credlmt_935A', 'dateofcredend_289D', 'dateofcredend_353D', 'dateofcredstart_181D', 'dateofcredstart_739D', 'dateofrealrepmt_138D', 'debtoutstand_525A', 'debtoverdue_47A', 'description_351M', 'dpdmax_139P', 'dpdmax_757P', 'dpdmaxdatemonth_442T', 'dpdmaxdatemonth_89T', 'dpdmaxdateyear_596T', 'dpdmaxdateyear_896T', 'financialinstitution_382M', 'financialinstitution_591M', 'instlamount_768A', 'instlamount_852A', 'interestrate_508L', 'lastupdate_1112D', 'lastupdate_388D', 'monthlyinstlamount_332A', 'monthlyinstlamount_674A', 'nominalrate_281L', 'nominalrate_498L', 'num_group1', 'numberofcontrsvalue_258L', 'numberofcontrsvalue_358L', 'numberofinstls_229L', 'numberofinstls_320L', 'numberofoutstandinstls_520L', 'numberofoutstandinstls_59L', 'numberofoverdueinstlmax_1039L', 'numberofoverdueinstlmax_1151L', 'numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D', 'numberofoverdueinstls_725L', 'numberofoverdueinstls_834L', 'outstandingamount_354A', 'outstandingamount_362A', 'overdueamount_31A', 'overdueamount_659A', 'overdueamountmax2_14A', 'overdueamountmax2_398A', 'overdueamountmax2date_1002D', 'overdueamountmax2date_1142D', 'overdueamountmax_155A', 'overdueamountmax_35A', 'overdueamountmaxdatemonth_284T', 'overdueamountmaxdatemonth_365T', 'overdueamountmaxdateyear_2T', 'overdueamountmaxdateyear_994T', 'periodicityofpmts_1102L', 'periodicityofpmts_837L', 'prolongationcount_1120L', 'prolongationcount_599L', 'purposeofcred_426M', 'purposeofcred_874M', 'refreshdate_3813885D', 'residualamount_488A', 'residualamount_856A', 'subjectrole_182M', 'subjectrole_93M', 'totalamount_6A', 'totalamount_996A', 'totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A']
Credit bureau a 1 1 Columns ['case_id', 'annualeffectiverate_199L', 'annualeffectiverate_63L', 'classificationofcontr_13M', 'classificationofcontr_400M', 'contractst_545M', 'contractst_964M', 'contractsum_5085717L', 'credlmt_230A', 'credlmt_935A', 'dateofcredend_289D', 'dateofcredend_353D', 'dateofcredstart_181D', 'dateofcredstart_739D', 'dateofrealrepmt_138D', 'debtoutstand_525A', 'debtoverdue_47A', 'description_351M', 'dpdmax_139P', 'dpdmax_757P', 'dpdmaxdatemonth_442T', 'dpdmaxdatemonth_89T', 'dpdmaxdateyear_596T', 'dpdmaxdateyear_896T', 'financialinstitution_382M', 'financialinstitution_591M', 'instlamount_768A', 'instlamount_852A', 'interestrate_508L', 'lastupdate_1112D', 'lastupdate_388D', 'monthlyinstlamount_332A', 'monthlyinstlamount_674A', 'nominalrate_281L', 'nominalrate_498L', 'num_group1', 'numberofcontrsvalue_258L', 'numberofcontrsvalue_358L', 'numberofinstls_229L', 'numberofinstls_320L', 'numberofoutstandinstls_520L', 'numberofoutstandinstls_59L', 'numberofoverdueinstlmax_1039L', 'numberofoverdueinstlmax_1151L', 'numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D', 'numberofoverdueinstls_725L', 'numberofoverdueinstls_834L', 'outstandingamount_354A', 'outstandingamount_362A', 'overdueamount_31A', 'overdueamount_659A', 'overdueamountmax2_14A', 'overdueamountmax2_398A', 'overdueamountmax2date_1002D', 'overdueamountmax2date_1142D', 'overdueamountmax_155A', 'overdueamountmax_35A', 'overdueamountmaxdatemonth_284T', 'overdueamountmaxdatemonth_365T', 'overdueamountmaxdateyear_2T', 'overdueamountmaxdateyear_994T', 'periodicityofpmts_1102L', 'periodicityofpmts_837L', 'prolongationcount_1120L', 'prolongationcount_599L', 'purposeofcred_426M', 'purposeofcred_874M', 'refreshdate_3813885D', 'residualamount_488A', 'residualamount_856A', 'subjectrole_182M', 'subjectrole_93M', 'totalamount_6A', 'totalamount_996A', 'totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A']
Credit bureau a 1 2 Columns ['case_id', 'annualeffectiverate_199L', 'annualeffectiverate_63L', 'classificationofcontr_13M', 'classificationofcontr_400M', 'contractst_545M', 'contractst_964M', 'contractsum_5085717L', 'credlmt_230A', 'credlmt_935A', 'dateofcredend_289D', 'dateofcredend_353D', 'dateofcredstart_181D', 'dateofcredstart_739D', 'dateofrealrepmt_138D', 'debtoutstand_525A', 'debtoverdue_47A', 'description_351M', 'dpdmax_139P', 'dpdmax_757P', 'dpdmaxdatemonth_442T', 'dpdmaxdatemonth_89T', 'dpdmaxdateyear_596T', 'dpdmaxdateyear_896T', 'financialinstitution_382M', 'financialinstitution_591M', 'instlamount_768A', 'instlamount_852A', 'interestrate_508L', 'lastupdate_1112D', 'lastupdate_388D', 'monthlyinstlamount_332A', 'monthlyinstlamount_674A', 'nominalrate_281L', 'nominalrate_498L', 'num_group1', 'numberofcontrsvalue_258L', 'numberofcontrsvalue_358L', 'numberofinstls_229L', 'numberofinstls_320L', 'numberofoutstandinstls_520L', 'numberofoutstandinstls_59L', 'numberofoverdueinstlmax_1039L', 'numberofoverdueinstlmax_1151L', 'numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D', 'numberofoverdueinstls_725L', 'numberofoverdueinstls_834L', 'outstandingamount_354A', 'outstandingamount_362A', 'overdueamount_31A', 'overdueamount_659A', 'overdueamountmax2_14A', 'overdueamountmax2_398A', 'overdueamountmax2date_1002D', 'overdueamountmax2date_1142D', 'overdueamountmax_155A', 'overdueamountmax_35A', 'overdueamountmaxdatemonth_284T', 'overdueamountmaxdatemonth_365T', 'overdueamountmaxdateyear_2T', 'overdueamountmaxdateyear_994T', 'periodicityofpmts_1102L', 'periodicityofpmts_837L', 'prolongationcount_1120L', 'prolongationcount_599L', 'purposeofcred_426M', 'purposeofcred_874M', 'refreshdate_3813885D', 'residualamount_488A', 'residualamount_856A', 'subjectrole_182M', 'subjectrole_93M', 'totalamount_6A', 'totalamount_996A', 'totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A']
Credit bureau a 1 3 Columns ['case_id', 'annualeffectiverate_199L', 'annualeffectiverate_63L', 'classificationofcontr_13M', 'classificationofcontr_400M', 'contractst_545M', 'contractst_964M', 'contractsum_5085717L', 'credlmt_230A', 'credlmt_935A', 'dateofcredend_289D', 'dateofcredend_353D', 'dateofcredstart_181D', 'dateofcredstart_739D', 'dateofrealrepmt_138D', 'debtoutstand_525A', 'debtoverdue_47A', 'description_351M', 'dpdmax_139P', 'dpdmax_757P', 'dpdmaxdatemonth_442T', 'dpdmaxdatemonth_89T', 'dpdmaxdateyear_596T', 'dpdmaxdateyear_896T', 'financialinstitution_382M', 'financialinstitution_591M', 'instlamount_768A', 'instlamount_852A', 'interestrate_508L', 'lastupdate_1112D', 'lastupdate_388D', 'monthlyinstlamount_332A', 'monthlyinstlamount_674A', 'nominalrate_281L', 'nominalrate_498L', 'num_group1', 'numberofcontrsvalue_258L', 'numberofcontrsvalue_358L', 'numberofinstls_229L', 'numberofinstls_320L', 'numberofoutstandinstls_520L', 'numberofoutstandinstls_59L', 'numberofoverdueinstlmax_1039L', 'numberofoverdueinstlmax_1151L', 'numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D', 'numberofoverdueinstls_725L', 'numberofoverdueinstls_834L', 'outstandingamount_354A', 'outstandingamount_362A', 'overdueamount_31A', 'overdueamount_659A', 'overdueamountmax2_14A', 'overdueamountmax2_398A', 'overdueamountmax2date_1002D', 'overdueamountmax2date_1142D', 'overdueamountmax_155A', 'overdueamountmax_35A', 'overdueamountmaxdatemonth_284T', 'overdueamountmaxdatemonth_365T', 'overdueamountmaxdateyear_2T', 'overdueamountmaxdateyear_994T', 'periodicityofpmts_1102L', 'periodicityofpmts_837L', 'prolongationcount_1120L', 'prolongationcount_599L', 'purposeofcred_426M', 'purposeofcred_874M', 'refreshdate_3813885D', 'residualamount_488A', 'residualamount_856A', 'subjectrole_182M', 'subjectrole_93M', 'totalamount_6A', 'totalamount_996A', 'totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A']

# EDA test sets

In [22]:
base_test.sample(7)

shape: (7, 4)
┌─────────┬───────────────┬────────┬──────────┐
│ case_id ┆ date_decision ┆ MONTH  ┆ WEEK_NUM │
│ ---     ┆ ---           ┆ ---    ┆ ---      │
│ i64     ┆ str           ┆ i64    ┆ i64      │
╞═════════╪═══════════════╪════════╪══════════╡
│ 57631   ┆ 2022-06-04    ┆ 202201 ┆ 100      │
│ 57634   ┆ 2021-01-27    ┆ 202201 ┆ 100      │
│ 57551   ┆ 2020-11-27    ┆ 202201 ┆ 100      │
│ 57630   ┆ 2021-03-16    ┆ 202201 ┆ 100      │
│ 57632   ┆ 2022-02-05    ┆ 202201 ┆ 100      │
│ 57633   ┆ 2022-01-25    ┆ 202201 ┆ 100      │
│ 57552   ┆ 2020-11-27    ┆ 202201 ┆ 100      │
└─────────┴───────────────┴────────┴──────────┘

In [23]:
static_1_test.sample(7)

shape: (7, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ i64     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ f64       ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│         ┆ f64        ┆ ---       ┆           ┆   ┆ f64       ┆           ┆           ┆           │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 57632   ┆ 0.0        ┆ 63647.402 ┆ 4732.0    ┆ … ┆ 7071.4    ┆ FO        ┆ null      ┆ null      │
│ 57569   ┆ 0.0        ┆ 0.0       ┆ 4682.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57631   ┆ 0.0        ┆ null      ┆ 2540.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57543   ┆ 0.0        ┆ 191767.36 ┆ 3674.6    ┆ … ┆ 17859.6   ┆ FO        ┆ AL        ┆ null      │
│ 57551   ┆ 0.0        ┆ 71036.4   ┆ 2844.6    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57639   ┆ 0.0        ┆ 142333.14 ┆ 12599.601 ┆ … ┆ 5588.0    ┆ BO        ┆ null      ┆ null      │
│ 57630   ┆ 0.0        ┆ 0.0       ┆ 8905.0    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [24]:
static_2_test.sample(7)

shape: (7, 168)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpdt ┆ amtinstpa ┆ annuity_7 ┆ … ┆ totinstal ┆ twobodfil ┆ typesuite ┆ validfrom │
│ ---     ┆ olerance_3 ┆ idbefduel ┆ 80A       ┆   ┆ last1m_45 ┆ ling_608L ┆ _864L     ┆ _1069D    │
│ i64     ┆ 44P        ┆ 24m_41871 ┆ ---       ┆   ┆ 25188A    ┆ ---       ┆ ---       ┆ ---       │
│         ┆ ---        ┆ 15A       ┆ f64       ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│         ┆ f64        ┆ ---       ┆           ┆   ┆ f64       ┆           ┆           ┆           │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 57636   ┆ 0.0        ┆ 0.0       ┆ 3366.4001 ┆ … ┆ null      ┆ FO        ┆ AL        ┆ null      │
│ 57647   ┆ 0.0        ┆ 116063.96 ┆ 3585.0    ┆ … ┆ 14070.0   ┆ FO        ┆ AL        ┆ null      │
│ 57641   ┆ 0.0        ┆ 173284.28 ┆ 8126.2    ┆ … ┆ 13446.4   ┆ FO        ┆ null      ┆ null      │
│ 57638   ┆ 0.0        ┆ 90741.14  ┆ 6129.8003 ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57633   ┆ 0.0        ┆ null      ┆ 8273.0    ┆ … ┆ null      ┆ FO        ┆ AL        ┆ null      │
│ 57634   ┆ 0.0        ┆ 39948.8   ┆ 1165.8    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
│ 57650   ┆ 0.0        ┆ 4570.166  ┆ 8984.4    ┆ … ┆ null      ┆ FO        ┆ null      ┆ null      │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [25]:
static_cb_test.sample(7)

shape: (7, 53)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ assignment ┆ assignmen ┆ assignmen ┆ … ┆ riskasses ┆ riskasses ┆ secondqua ┆ thirdquar │
│ ---     ┆ date_238D  ┆ tdate_452 ┆ tdate_495 ┆   ┆ ment_302T ┆ ment_940T ┆ rter_766L ┆ ter_1082L │
│ i64     ┆ ---        ┆ 7235D     ┆ 5616D     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ str        ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ f64       ┆ f64       │
│         ┆            ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 57543   ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.0       ┆ 3.0       │
│ 57631   ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.0       ┆ 5.0       │
│ 57569   ┆ null       ┆ null      ┆ 2011-10-1 ┆ … ┆ null      ┆ null      ┆ 1.0       ┆ 3.0       │
│         ┆            ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 57634   ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ 1.0       │
│ 57630   ┆ null       ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 4.0       ┆ 1.0       │
│ 57549   ┆ null       ┆ null      ┆ 2018-05-0 ┆ … ┆ null      ┆ null      ┆ 8.0       ┆ 2.0       │
│         ┆            ┆           ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│ 57552   ┆ null       ┆ null      ┆ 2018-11-1 ┆ … ┆ null      ┆ null      ┆ 7.0       ┆ 1.0       │
│         ┆            ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [26]:
# Shape of test sets
print('Depth = 0')
df_shape("Base", base_test)
df_shape("Static 1", static_1_test)
df_shape("Static 2", static_2_test)
df_shape("Static cb", static_cb_test)
print('=============================================================')
print('Depth = 1')
df_shape("Applprev 1 0", applprev_1_0_test)
df_shape("Applprev 1 1", applprev_1_1_test)

df_shape("Other", other_test)

df_shape("Tax registry a", tax_registry_a_test)
df_shape("Tax registry b", tax_registry_b_test)
df_shape("Tax registry c", tax_registry_c_test)

df_shape("Credit bureau a 1 0", credit_bureau_a_1_0_test)
df_shape("Credit bureau a 1 1", credit_bureau_a_1_1_test)
df_shape("Credit bureau a 1 2", credit_bureau_a_1_2_test)
df_shape("Credit bureau a 1 3", credit_bureau_a_1_3_test)
df_shape("Credit bureau b 1", credit_bureau_b_1_test)

df_shape("Deposite", deposit_test)

df_shape("Person 1", person_1_test)

df_shape("Debitcard", debitcard_test)
print('=============================================================')
print('Depth = 2')
df_shape("Person 2", person_2_test)
df_shape("Applprev 2", applprev_2_test)
df_shape("Credit bureau a 2 0", credit_bureau_a_2_0_test)
df_shape("Credit bureau a 2 1", credit_bureau_a_2_1_test)
df_shape("Credit bureau b 2", credit_bureau_b_2_test)

Depth = 0
Base shape: (10, 4)
Static 1 shape: (10, 168)
Static 2 shape: (10, 168)
Static cb shape: (10, 53)
=============================================================
Depth = 1
Applprev 1 0 shape: (10, 41)
Applprev 1 1 shape: (10, 41)
Other shape: (10, 7)
Tax registry a shape: (10, 5)
Tax registry b shape: (10, 5)
Tax registry c shape: (0, 5)
Credit bureau a 1 0 shape: (10, 79)
Credit bureau a 1 1 shape: (10, 79)
Credit bureau a 1 2 shape: (10, 79)
Credit bureau a 1 3 shape: (10, 79)
Credit bureau b 1 shape: (10, 45)
Deposite shape: (10, 5)
Person 1 shape: (10, 37)
Debitcard shape: (10, 6)
=============================================================
Depth = 2
Person 2 shape: (10, 11)
Applprev 2 shape: (10, 6)
Credit bureau a 2 0 shape: (10, 19)
Credit bureau a 2 1 shape: (10, 19)
Credit bureau b 2 shape: (10, 6)

In [27]:
# Data types for test sets
print('Depth = 0')
df_data_types("Base", base_test)
df_data_types("Static 1", static_1_test)
df_data_types("Static 2", static_2_test)
df_data_types("Static cb", static_cb_test)
print('=============================================================')
print('Depth = 1')
df_data_types("Applprev 1 0", applprev_1_0_test)
df_data_types("Applprev 1 1", applprev_1_1_test)

df_data_types("Other", other_test)

df_data_types("Tax registry a", tax_registry_a_test)
df_data_types("Tax registry b", tax_registry_b_test)
df_data_types("Tax registry c", tax_registry_c_test)

df_data_types("Credit bureau a 1 0", credit_bureau_a_1_0_test)
df_data_types("Credit bureau a 1 1", credit_bureau_a_1_1_test)
df_data_types("Credit bureau a 1 2", credit_bureau_a_1_2_test)
df_data_types("Credit bureau a 1 3", credit_bureau_a_1_3_test)
df_data_types("Credit bureau b 1", credit_bureau_b_1_test)

df_data_types("Deposite", deposit_test)

df_data_types("Person 1", person_1_test)

df_data_types("Debitcard", debitcard_test)
print('=============================================================')
print('Depth = 2')
df_data_types("Person 2", person_2_test)
df_data_types("Applprev 2", applprev_2_test)
df_data_types("Credit bureau a 2 0", credit_bureau_a_2_0_test)
df_data_types("Credit bureau a 2 1", credit_bureau_a_2_1_test)
df_data_types("Credit bureau b 2", credit_bureau_b_2_test)

Depth = 0
Base data types: Counter({Int64: 3, String: 1})
Static 1 data types: Counter({Float64: 122, String: 40, Boolean: 5, Int64: 1})
Static 2 data types: Counter({Float64: 120, String: 43, Boolean: 4, Int64: 1})
Static cb data types: Counter({String: 39, Float64: 13, Int64: 1})
=============================================================
Depth = 1
Applprev 1 0 data types: Counter({String: 25, Float64: 13, Int64: 2, Boolean: 1})
Applprev 1 1 data types: Counter({String: 19, Float64: 18, Int64: 2, Boolean: 2})
Other data types: Counter({Float64: 5, Int64: 2})
Tax registry a data types: Counter({Int64: 2, String: 2, Float64: 1})
Tax registry b data types: Counter({Int64: 2, String: 2, Float64: 1})
Tax registry c data types: Counter({String: 5})
Credit bureau a 1 0 data types: Counter({Float64: 44, String: 33, Int64: 2})
Credit bureau a 1 1 data types: Counter({Float64: 51, String: 26, Int64: 2})
Credit bureau a 1 2 data types: Counter({Float64: 48, String: 29, Int64: 2})
Credit bureau a 1 3 data types: Counter({Float64: 53, String: 25, Int64: 1})
Credit bureau b 1 data types: Counter({Float64: 30, String: 13, Int64: 2})
Deposite data types: Counter({Int64: 2, String: 2, Float64: 1})
Person 1 data types: Counter({String: 25, Float64: 5, Boolean: 5, Int64: 2})
Debitcard data types: Counter({String: 4, Int64: 2})
=============================================================
Depth = 2
Person 2 data types: Counter({String: 8, Int64: 3})
Applprev 2 data types: Counter({Int64: 3, String: 3})
Credit bureau a 2 0 data types: Counter({String: 10, Float64: 6, Int64: 3})
Credit bureau a 2 1 data types: Counter({Float64: 10, String: 6, Int64: 3})
Credit bureau b 2 data types: Counter({Int64: 3, Float64: 2, String: 1})